deps_config := \
	target/device/Atmel/arch-avr32/Config.in.linux.patches \
	target/device/Atmel/arch-arm/Config.in.linux.patches \
	target/device/Atmel/Config.in.linux.patches \
	target/device/Config.in.linux.patches \
	target/linux/Config.in.versions \
	target/linux/Config.in.advanced \
	target/linux/Config.in \
	target/device/Atmel/arch-arm/u-boot/Config.in \
	target/device/Config.in.u-boot \
	target/u-boot/Config.in \
	target/powerpc/yaboot/Config.in \
	target/x86/syslinux/Config.in \
	target/x86/grub/Config.in \
	target/romfs/Config.in \
	target/initramfs/Config.in \
	target/iso9660/Config.in \
	target/cpio/Config.in \
	target/tar/Config.in \
	target/squashfs/Config.in \
	target/ubifs/Config.in \
	target/jffs2/Config.in \
	target/ext2/Config.in \
	target/cloop/Config.in \
	target/cramfs/Config.in \
	target/Config.in \
	package/games/xboard/Config.in \
	package/games/vice/Config.in \
	package/games/rubix/Config.in \
	package/games/prboom/Config.in \
	package/games/magiccube4d/Config.in \
	package/games/lxdoom/Config.in \
	package/games/gnuchess/Config.in \
	package/games/doom-wad/Config.in \
	package/games/ace_of_penguins/Config.in \
	package/games/Config.in \
	package/java/concierge/Config.in \
	package/java/jamvm/Config.in \
	package/java/classpath/Config.in \
	package/java/Config.in \
	package/xerces/Config.in \
	package/libxslt/Config.in \
	package/libxml2/Config.in \
	package/ezxml/Config.in \
	package/expat/Config.in \
	package/php/Config.ext \
	package/php/Config.in \
	package/tcl/Config.in \
	package/ruby/Config.in \
	package/python/Config.in \
	package/microperl/Config.in \
	package/lua/Config.in \
	package/rpm/Config.in \
	package/portage/Config.in \
	package/ipkg/Config.in \
	package/zlib/Config.in \
	package/unrar/Config.in \
	package/lzma/Config.in \
	package/lzop/Config.in \
	package/lzo/Config.in \
	package/gzip/Config.in \
	package/xvkbd/Config.in \
	package/xstroke/Config.in \
	package/xpdf/Config.in \
	package/x11vnc/Config.in \
	package/torsmo/Config.in \
	package/synergy/Config.in \
	package/sylpheed/Config.in \
	package/rxvt/Config.in \
	package/rdesktop/Config.in \
	package/pcmanfm/Config.in \
	package/midori/Config.in \
	package/leafpad/Config.in \
	package/gtkperf/Config.in \
	package/gob2/Config.in \
	package/gmpc/Config.in \
	package/gqview/Config.in \
	package/docker/Config.in \
	package/dillo/Config.in \
	package/alsamixergui/Config.in \
	package/blackbox/Config.in \
	package/metacity/Config.in \
	package/matchbox/Config.in \
	package/webkit/Config.in \
	package/tslib/Config.in \
	package/freetype/Config.in \
	package/fontconfig/Config.in \
	package/openmotif/Config.in \
	package/fltk/Config.in \
	package/libsexy/Config.in \
	package/gtk2-themes/Config.in \
	package/gtk2-engines/Config.in \
	package/libgtk2/Config.in \
	package/libgtk12/Config.in \
	package/libglib2/Config.in \
	package/libglib12/Config.in \
	package/libglade/Config.in \
	package/liberation/Config.in \
	package/libdrm/Config.in \
	package/pango/Config.in \
	package/cairo/Config.in \
	package/atk/Config.in \
	package/x11r7/xkeyboard-config/Config.in \
	package/x11r7/xdata_xcursor-themes/Config.in \
	package/x11r7/xdata_xbitmaps/Config.in \
	package/x11r7/mcookie/Config.in \
	package/x11r7/xutil_util-macros/Config.in \
	package/x11r7/xutil_makedepend/Config.in \
	package/x11r7/xproto_xproxymanagementprotocol/Config.in \
	package/x11r7/xproto_xproto/Config.in \
	package/x11r7/xproto_xineramaproto/Config.in \
	package/x11r7/xproto_xf86vidmodeproto/Config.in \
	package/x11r7/xproto_xf86rushproto/Config.in \
	package/x11r7/xproto_xf86miscproto/Config.in \
	package/x11r7/xproto_xf86driproto/Config.in \
	package/x11r7/xproto_xf86dgaproto/Config.in \
	package/x11r7/xproto_xf86bigfontproto/Config.in \
	package/x11r7/xproto_xextproto/Config.in \
	package/x11r7/xproto_xcmiscproto/Config.in \
	package/x11r7/xproto_windowswmproto/Config.in \
	package/x11r7/xproto_videoproto/Config.in \
	package/x11r7/xproto_trapproto/Config.in \
	package/x11r7/xproto_scrnsaverproto/Config.in \
	package/x11r7/xproto_resourceproto/Config.in \
	package/x11r7/xproto_renderproto/Config.in \
	package/x11r7/xproto_recordproto/Config.in \
	package/x11r7/xproto_randrproto/Config.in \
	package/x11r7/xproto_printproto/Config.in \
	package/x11r7/xproto_kbproto/Config.in \
	package/x11r7/xproto_inputproto/Config.in \
	package/x11r7/xproto_glproto/Config.in \
	package/x11r7/xproto_fontsproto/Config.in \
	package/x11r7/xproto_fontcacheproto/Config.in \
	package/x11r7/xproto_fixesproto/Config.in \
	package/x11r7/xproto_evieext/Config.in \
	package/x11r7/xproto_dmxproto/Config.in \
	package/x11r7/xproto_damageproto/Config.in \
	package/x11r7/xproto_compositeproto/Config.in \
	package/x11r7/xproto_bigreqsproto/Config.in \
	package/x11r7/xproto_applewmproto/Config.in \
	package/x11r7/xcb-proto/Config.in \
	package/x11r7/xfont_font-xfree86-type1/Config.in \
	package/x11r7/xfont_font-winitzki-cyrillic/Config.in \
	package/x11r7/xfont_font-sun-misc/Config.in \
	package/x11r7/xfont_font-sony-misc/Config.in \
	package/x11r7/xfont_font-screen-cyrillic/Config.in \
	package/x11r7/xfont_font-schumacher-misc/Config.in \
	package/x11r7/xfont_font-mutt-misc/Config.in \
	package/x11r7/xfont_font-misc-misc/Config.in \
	package/x11r7/xfont_font-misc-meltho/Config.in \
	package/x11r7/xfont_font-misc-ethiopic/Config.in \
	package/x11r7/xfont_font-misc-cyrillic/Config.in \
	package/x11r7/xfont_font-micro-misc/Config.in \
	package/x11r7/xfont_font-jis-misc/Config.in \
	package/x11r7/xfont_font-isas-misc/Config.in \
	package/x11r7/xfont_font-ibm-type1/Config.in \
	package/x11r7/xfont_font-dec-misc/Config.in \
	package/x11r7/xfont_font-daewoo-misc/Config.in \
	package/x11r7/xfont_font-cursor-misc/Config.in \
	package/x11r7/xfont_font-cronyx-cyrillic/Config.in \
	package/x11r7/xfont_font-bitstream-type1/Config.in \
	package/x11r7/xfont_font-bitstream-speedo/Config.in \
	package/x11r7/xfont_font-bitstream-75dpi/Config.in \
	package/x11r7/xfont_font-bitstream-100dpi/Config.in \
	package/x11r7/xfont_font-bh-type1/Config.in \
	package/x11r7/xfont_font-bh-ttf/Config.in \
	package/x11r7/xfont_font-bh-lucidatypewriter-75dpi/Config.in \
	package/x11r7/xfont_font-bh-lucidatypewriter-100dpi/Config.in \
	package/x11r7/xfont_font-bh-75dpi/Config.in \
	package/x11r7/xfont_font-bh-100dpi/Config.in \
	package/x11r7/xfont_font-arabic-misc/Config.in \
	package/x11r7/xfont_font-alias/Config.in \
	package/x11r7/xfont_font-adobe-utopia-type1/Config.in \
	package/x11r7/xfont_font-adobe-utopia-75dpi/Config.in \
	package/x11r7/xfont_font-adobe-utopia-100dpi/Config.in \
	package/x11r7/xfont_font-adobe-75dpi/Config.in \
	package/x11r7/xfont_font-adobe-100dpi/Config.in \
	package/x11r7/xfont_encodings/Config.in \
	package/x11r7/xfont_font-util/Config.in \
	package/x11r7/xdriver_xf86-video-xgixp/Config.in \
	package/x11r7/xdriver_xf86-video-xgi/Config.in \
	package/x11r7/xdriver_xf86-video-wsfb/Config.in \
	package/x11r7/xdriver_xf86-video-voodoo/Config.in \
	package/x11r7/xdriver_xf86-video-vmware/Config.in \
	package/x11r7/xdriver_xf86-video-vesa/Config.in \
	package/x11r7/xdriver_xf86-video-vermilion/Config.in \
	package/x11r7/xdriver_xf86-video-v4l/Config.in \
	package/x11r7/xdriver_xf86-video-tseng/Config.in \
	package/x11r7/xdriver_xf86-video-trident/Config.in \
	package/x11r7/xdriver_xf86-video-tga/Config.in \
	package/x11r7/xdriver_xf86-video-tdfx/Config.in \
	package/x11r7/xdriver_xf86-video-suntcx/Config.in \
	package/x11r7/xdriver_xf86-video-sunleo/Config.in \
	package/x11r7/xdriver_xf86-video-sunffb/Config.in \
	package/x11r7/xdriver_xf86-video-suncg6/Config.in \
	package/x11r7/xdriver_xf86-video-suncg3/Config.in \
	package/x11r7/xdriver_xf86-video-suncg14/Config.in \
	package/x11r7/xdriver_xf86-video-sunbw2/Config.in \
	package/x11r7/xdriver_xf86-video-sisusb/Config.in \
	package/x11r7/xdriver_xf86-video-sis/Config.in \
	package/x11r7/xdriver_xf86-video-siliconmotion/Config.in \
	package/x11r7/xdriver_xf86-video-savage/Config.in \
	package/x11r7/xdriver_xf86-video-s3virge/Config.in \
	package/x11r7/xdriver_xf86-video-s3/Config.in \
	package/x11r7/xdriver_xf86-video-rendition/Config.in \
	package/x11r7/xdriver_xf86-video-r128/Config.in \
	package/x11r7/xdriver_xf86-video-openchrome/Config.in \
	package/x11r7/xdriver_xf86-video-nv/Config.in \
	package/x11r7/xdriver_xf86-video-newport/Config.in \
	package/x11r7/xdriver_xf86-video-neomagic/Config.in \
	package/x11r7/xdriver_xf86-video-mga/Config.in \
	package/x11r7/xdriver_xf86-video-mach64/Config.in \
	package/x11r7/xdriver_xf86-video-intel/Config.in \
	package/x11r7/xdriver_xf86-video-impact/Config.in \
	package/x11r7/xdriver_xf86-video-i740/Config.in \
	package/x11r7/xdriver_xf86-video-i128/Config.in \
	package/x11r7/xdriver_xf86-video-glint/Config.in \
	package/x11r7/xdriver_xf86-video-glide/Config.in \
	package/x11r7/xdriver_xf86-video-geode/Config.in \
	package/x11r7/xdriver_xf86-video-fbdev/Config.in \
	package/x11r7/xdriver_xf86-video-dummy/Config.in \
	package/x11r7/xdriver_xf86-video-cirrus/Config.in \
	package/x11r7/xdriver_xf86-video-chips/Config.in \
	package/x11r7/xdriver_xf86-video-ati/Config.in \
	package/x11r7/xdriver_xf86-video-ast/Config.in \
	package/x11r7/xdriver_xf86-video-ark/Config.in \
	package/x11r7/xdriver_xf86-video-apm/Config.in \
	package/x11r7/xdriver_xf86-input-void/Config.in \
	package/x11r7/xdriver_xf86-input-vmmouse/Config.in \
	package/x11r7/xdriver_xf86-input-synaptics/Config.in \
	package/x11r7/xdriver_xf86-input-mouse/Config.in \
	package/x11r7/xdriver_xf86-input-keyboard/Config.in \
	package/x11r7/xdriver_xf86-input-joystick/Config.in \
	package/x11r7/xdriver_xf86-input-evdev/Config.in \
	package/x11r7/xdriver_xf86-input-aiptek/Config.in \
	package/x11r7/xdriver_xf86-input-acecad/Config.in \
	package/x11r7/xapp_xwud/Config.in \
	package/x11r7/xapp_xwininfo/Config.in \
	package/x11r7/xapp_xwd/Config.in \
	package/x11r7/xapp_xvinfo/Config.in \
	package/x11r7/xapp_xvidtune/Config.in \
	package/x11r7/xapp_xtrap/Config.in \
	package/x11r7/xapp_xstdcmap/Config.in \
	package/x11r7/xapp_xsm/Config.in \
	package/x11r7/xapp_xsetroot/Config.in \
	package/x11r7/xapp_xsetpointer/Config.in \
	package/x11r7/xapp_xsetmode/Config.in \
	package/x11r7/xapp_xset/Config.in \
	package/x11r7/xapp_xrx/Config.in \
	package/x11r7/xapp_xrefresh/Config.in \
	package/x11r7/xapp_xrdb/Config.in \
	package/x11r7/xapp_xrandr/Config.in \
	package/x11r7/xapp_xprop/Config.in \
	package/x11r7/xapp_xprehashprinterlist/Config.in \
	package/x11r7/xapp_xpr/Config.in \
	package/x11r7/xapp_xplsprinters/Config.in \
	package/x11r7/xapp_xphelloworld/Config.in \
	package/x11r7/xapp_xmore/Config.in \
	package/x11r7/xapp_xmodmap/Config.in \
	package/x11r7/xapp_xmh/Config.in \
	package/x11r7/xapp_xmessage/Config.in \
	package/x11r7/xapp_xman/Config.in \
	package/x11r7/xapp_xmag/Config.in \
	package/x11r7/xapp_xlsfonts/Config.in \
	package/x11r7/xapp_xlsclients/Config.in \
	package/x11r7/xapp_xlsatoms/Config.in \
	package/x11r7/xapp_xlogo/Config.in \
	package/x11r7/xapp_xload/Config.in \
	package/x11r7/xapp_xkill/Config.in \
	package/x11r7/xapp_xkbutils/Config.in \
	package/x11r7/xapp_xkbprint/Config.in \
	package/x11r7/xapp_xkbevd/Config.in \
	package/x11r7/xapp_xkbcomp/Config.in \
	package/x11r7/xapp_xinput/Config.in \
	package/x11r7/xapp_xinit/Config.in \
	package/x11r7/xapp_xhost/Config.in \
	package/x11r7/xapp_xgc/Config.in \
	package/x11r7/xapp_xgamma/Config.in \
	package/x11r7/xapp_xfwp/Config.in \
	package/x11r7/xapp_xfsinfo/Config.in \
	package/x11r7/xapp_xfs/Config.in \
	package/x11r7/xapp_xfontsel/Config.in \
	package/x11r7/xapp_xfindproxy/Config.in \
	package/x11r7/xapp_xfd/Config.in \
	package/x11r7/xapp_xf86dga/Config.in \
	package/x11r7/xapp_xeyes/Config.in \
	package/x11r7/xapp_xev/Config.in \
	package/x11r7/xapp_xedit/Config.in \
	package/x11r7/xapp_xdriinfo/Config.in \
	package/x11r7/xapp_xdpyinfo/Config.in \
	package/x11r7/xapp_xdm/Config.in \
	package/x11r7/xapp_xditview/Config.in \
	package/x11r7/xapp_xdbedizzy/Config.in \
	package/x11r7/xapp_xcursorgen/Config.in \
	package/x11r7/xapp_xcmsdb/Config.in \
	package/x11r7/xapp_xclock/Config.in \
	package/x11r7/xapp_xclipboard/Config.in \
	package/x11r7/xapp_xcalc/Config.in \
	package/x11r7/xapp_xbiff/Config.in \
	package/x11r7/xapp_xbacklight/Config.in \
	package/x11r7/xapp_xauth/Config.in \
	package/x11r7/xapp_x11perf/Config.in \
	package/x11r7/xapp_viewres/Config.in \
	package/x11r7/xapp_twm/Config.in \
	package/x11r7/xapp_smproxy/Config.in \
	package/x11r7/xapp_showfont/Config.in \
	package/x11r7/xapp_setxkbmap/Config.in \
	package/x11r7/xapp_sessreg/Config.in \
	package/x11r7/xapp_scripts/Config.in \
	package/x11r7/xapp_rstart/Config.in \
	package/x11r7/xapp_rgb/Config.in \
	package/x11r7/xapp_proxymngr/Config.in \
	package/x11r7/xapp_oclock/Config.in \
	package/x11r7/xapp_mkfontscale/Config.in \
	package/x11r7/xapp_mkfontdir/Config.in \
	package/x11r7/xapp_luit/Config.in \
	package/x11r7/xapp_listres/Config.in \
	package/x11r7/xapp_lbxproxy/Config.in \
	package/x11r7/xapp_ico/Config.in \
	package/x11r7/xapp_iceauth/Config.in \
	package/x11r7/xapp_fstobdf/Config.in \
	package/x11r7/xapp_fslsfonts/Config.in \
	package/x11r7/xapp_fonttosfnt/Config.in \
	package/x11r7/xapp_editres/Config.in \
	package/x11r7/xapp_bitmap/Config.in \
	package/x11r7/xapp_beforelight/Config.in \
	package/x11r7/xapp_bdftopcf/Config.in \
	package/x11r7/xapp_appres/Config.in \
	package/x11r7/xlib_libpciaccess/Config.in \
	package/x11r7/xlib_xtrans/Config.in \
	package/x11r7/xlib_libxkbui/Config.in \
	package/x11r7/xlib_libxkbfile/Config.in \
	package/x11r7/xlib_liboldX/Config.in \
	package/x11r7/xlib_liblbxutil/Config.in \
	package/x11r7/xlib_libfontenc/Config.in \
	package/x11r7/xlib_libdmx/Config.in \
	package/x11r7/xlib_libXxf86vm/Config.in \
	package/x11r7/xlib_libXxf86misc/Config.in \
	package/x11r7/xlib_libXxf86dga/Config.in \
	package/x11r7/xlib_libXvMC/Config.in \
	package/x11r7/xlib_libXv/Config.in \
	package/x11r7/xlib_libXtst/Config.in \
	package/x11r7/xlib_libXt/Config.in \
	package/x11r7/xlib_libXres/Config.in \
	package/x11r7/xlib_libXrender/Config.in \
	package/x11r7/xlib_libXrandr/Config.in \
	package/x11r7/xlib_libXprintUtil/Config.in \
	package/x11r7/xlib_libXprintAppUtil/Config.in \
	package/x11r7/xlib_libXpm/Config.in \
	package/x11r7/xlib_libXp/Config.in \
	package/x11r7/xlib_libXmu/Config.in \
	package/x11r7/xlib_libXinerama/Config.in \
	package/x11r7/xlib_libXi/Config.in \
	package/x11r7/xlib_libXft/Config.in \
	package/x11r7/xlib_libXfontcache/Config.in \
	package/x11r7/xlib_libXfont/Config.in \
	package/x11r7/xlib_libXfixes/Config.in \
	package/x11r7/xlib_libXext/Config.in \
	package/x11r7/xlib_libXevie/Config.in \
	package/x11r7/xlib_libXdmcp/Config.in \
	package/x11r7/xlib_libXdamage/Config.in \
	package/x11r7/xlib_libXcursor/Config.in \
	package/x11r7/xlib_libXcomposite/Config.in \
	package/x11r7/xlib_libXaw/Config.in \
	package/x11r7/xlib_libXau/Config.in \
	package/x11r7/xlib_libXTrap/Config.in \
	package/x11r7/xlib_libXScrnSaver/Config.in \
	package/x11r7/xlib_libX11/Config.in \
	package/x11r7/xlib_libSM/Config.in \
	package/x11r7/xlib_libICE/Config.in \
	package/x11r7/xlib_libFS/Config.in \
	package/x11r7/xcb-util/Config.in \
	package/x11r7/pthread-stubs/Config.in \
	package/x11r7/mesa3d/Config.in \
	package/x11r7/libxcb/Config.in \
	package/x11r7/xserver_xorg-server/Config.in \
	package/x11r7/Config.in \
	package/qt/Config.mouse.in \
	package/qt/Config.gfx.in \
	package/qt/Config.sql.in \
	package/qt/Config.in \
	package/fbset/Config.in \
	package/fbv/Config.in \
	package/tiff/Config.in \
	package/sdl_gfx/Config.in \
	package/sdl_ttf/Config.in \
	package/sdl_net/Config.in \
	package/sdl_mixer/Config.in \
	package/sdl_image/Config.in \
	package/sdl/Config.in \
	package/sawman/Config.in \
	package/pixman/Config.in \
	package/lite/Config.in \
	package/linux-fusion/Config.in \
	package/libungif/Config.in \
	package/libpng/Config.in \
	package/libart/Config.in \
	package/jpeg/Config.in \
	package/imagemagick/Config.in \
	package/fbdump/Config.in \
	package/directfb-examples/Config.in \
	package/directfb/Config.in \
	package/dialog/Config.in \
	package/slang/Config.in \
	package/newt/Config.in \
	package/ncurses/Config.in \
	package/multimedia/vlc/Config.in \
	package/multimedia/ushare/Config.in \
	package/multimedia/taglib/Config.in \
	package/multimedia/festival/voices/Config.in \
	package/multimedia/festival/lexicons/Config.in \
	package/multimedia/festival/speech-tools/Config.in \
	package/multimedia/festival/Config.in \
	package/multimedia/speex/Config.in \
	package/multimedia/mplayer/Config.in \
	package/multimedia/mpg123/Config.in \
	package/multimedia/mediatomb/Config.in \
	package/multimedia/madplay/Config.in \
	package/multimedia/libvorbis/Config.in \
	package/multimedia/libtheora/Config.in \
	package/multimedia/libsndfile/Config.in \
	package/multimedia/libogg/Config.in \
	package/multimedia/libmpd/Config.in \
	package/multimedia/libmms/Config.in \
	package/multimedia/libmad/Config.in \
	package/multimedia/libid3tag/Config.in \
	package/multimedia/gst-plugins-ugly/Config.in \
	package/multimedia/gst-plugins-bad/Config.in \
	package/multimedia/gst-plugins-good/Config.in \
	package/multimedia/gst-plugins-base/Config.in \
	package/multimedia/gstreamer/Config.in \
	package/multimedia/flac/Config.in \
	package/multimedia/aumix/Config.in \
	package/multimedia/asterisk/Config.in \
	package/multimedia/alsa-utils/Config.in \
	package/multimedia/alsa-lib/Config.in \
	package/multimedia/Config.in \
	package/xfsprogs/Config.in \
	package/wipe/Config.in \
	package/usbutils/Config.in \
	package/usbmount/Config.in \
	package/unionfs-utils/Config.in \
	package/udev/Config.in \
	package/smartmontools/Config.in \
	package/sg3_utils/Config.in \
	package/sfdisk/Config.in \
	package/setserial/Config.in \
	package/pcmcia/Config.in \
	package/pciutils/Config.in \
	package/ntfsprogs/Config.in \
	package/ntfs-3g/Config.in \
	package/mtd/Config.in \
	package/memtester/Config.in \
	package/mdadm/Config.in \
	package/lvm2/Config.in \
	package/lm-sensors/Config.in \
	package/libusb/Config.in \
	package/libraw1394/Config.in \
	package/libfuse/Config.in \
	package/libaio/Config.in \
	package/iostat/Config.in \
	package/input-tools/Config.in \
	package/i2c-tools/Config.in \
	package/hwdata/Config.in \
	package/hddtemp/Config.in \
	package/hotplug/Config.in \
	package/hdparm/Config.in \
	package/hal/Config.in \
	package/gadgetfs-test/Config.in \
	package/fis/Config.in \
	package/fconfig/Config.in \
	package/eeprog/Config.in \
	package/e2fsprogs/Config.in \
	package/dosfstools/Config.in \
	package/dmraid/Config.in \
	package/devmem2/Config.in \
	package/dbus-python/Config.in \
	package/dbus-glib/Config.in \
	package/dbus/Config.in \
	package/aufs2-util/Config.in \
	package/acpid/Config.in \
	package/Alt-F-utils/Config.in \
	package/wpa_supplicant/Config.in \
	package/wireless-tools/Config.in \
	package/wget/Config.in \
	package/webif/Config.in \
	package/vtun/Config.in \
	package/vsftpd/Config.in \
	package/vpnc/Config.in \
	package/udpcast/Config.in \
	package/ttcp/Config.in \
	package/transmission/Config.in \
	package/tn5250/Config.in \
	package/tinyhttpd/Config.in \
	package/thttpd/Config.in \
	package/tftpd/Config.in \
	package/tcpdump/Config.in \
	package/stunnel/Config.in \
	package/spawn-fcgi/Config.in \
	package/socat/Config.in \
	package/samba/Config.in \
	package/rsync/Config.in \
	package/quagga/Config.in \
	package/proftpd/Config.in \
	package/pptp-linux/Config.in \
	package/rp-pppoe/Config.in \
	package/radvd/Config.in \
	package/pppd/Config.in \
	package/portmap/Config.in \
	package/openswan/Config.in \
	package/openvpn/Config.in \
	package/openssl/Config.in \
	package/openssh/Config.in \
	package/openntpd/Config.in \
	package/olsr/Config.in \
	package/ntp/Config.in \
	package/nfs-utils/Config.in \
	package/netstat-nat/Config.in \
	package/netsnmp/Config.in \
	package/netplug/Config.in \
	package/netkittelnet/Config.in \
	package/netkitbase/Config.in \
	package/netcat/Config.in \
	package/neon/Config.in \
	package/ncftp/Config.in \
	package/nbd/Config.in \
	package/mutt/Config.in \
	package/msmtp/Config.in \
	package/mrouted/Config.in \
	package/mii-diag/Config.in \
	package/microcom/Config.in \
	package/mdnsresponder/Config.in \
	package/lrzsz/Config.in \
	package/links/Config.in \
	package/lighttpd/Config.in \
	package/libupnp/Config.in \
	package/libsoup/Config.in \
	package/libpcap/Config.in \
	package/libosip2/Config.in \
	package/libnl/Config.in \
	package/libeXosip2/Config.in \
	package/libesmtp/Config.in \
	package/libdnet/Config.in \
	package/libcurl/Config.in \
	package/libcgicc/Config.in \
	package/libcgi/Config.in \
	package/l2tp/Config.in \
	package/kismet/Config.in \
	package/iw/Config.in \
	package/inadyn/Config.in \
	package/iptables/Config.in \
	package/ipsec-tools/Config.in \
	package/iproute2/Config.in \
	package/iperf/Config.in \
	package/ifplugd/Config.in \
	package/hostap/Config.in \
	package/haserl/Config.in \
	package/fuppes/Config.in \
	package/ethtool/Config.in \
	package/esmtp/Config.in \
	package/dropbear/Config.in \
	package/dnsmasq/Config.in \
	package/dhcp/Config.in \
	package/ctorrent/Config.in \
	package/bridge-utils/Config.in \
	package/bmon/Config.in \
	package/bind/Config.in \
	package/boa/Config.in \
	package/axel/Config.in \
	package/avahi/Config.in \
	package/argus/Config.in \
	package/editors/vim/Config.in \
	package/editors/uemacs/Config.in \
	package/editors/nano/Config.in \
	package/editors/ed/Config.in \
	package/editors/Config.in \
	package/database/sqlite/Config.in \
	package/database/mysql_client/Config.in \
	package/database/Config.in \
	package/which/Config.in \
	package/util-linux/Config.in \
	package/sysvinit/Config.in \
	package/sysklogd/Config.in \
	package/sudo/Config.in \
	package/strace/Config.in \
	package/startup-notification/Config.in \
	package/shared-mime-info/Config.in \
	package/screen/Config.in \
	package/psmisc/Config.in \
	package/procps/Config.in \
	package/popt/Config.in \
	package/ng-spice-rework/Config.in \
	package/modutils/Config.in \
	package/module-init-tools/Config.in \
	package/memstat/Config.in \
	package/ltrace/Config.in \
	package/ltp-testsuite/Config.in \
	package/lsof/Config.in \
	package/logrotate/Config.in \
	package/lockfile-progs/Config.in \
	package/libsysfs/Config.in \
	package/liboil/Config.in \
	package/liblockfile/Config.in \
	package/libidn/Config.in \
	package/libiconv/Config.in \
	package/libgpg-error/Config.in \
	package/libgcrypt/Config.in \
	package/libfloat/Config.in \
	package/libevent/Config.in \
	package/libelf/Config.in \
	package/libdaemon/Config.in \
	package/libconfuse/Config.in \
	package/libconfig/Config.in \
	package/less/Config.in \
	package/kexec/Config.in \
	package/icu/Config.in \
	package/gamin/Config.in \
	package/file/Config.in \
	package/enchant/Config.in \
	package/dash/Config.in \
	package/customize/Config.in \
	package/cups/Config.in \
	package/bootutils/Config.in \
	package/bsdiff/Config.in \
	package/berkeleydb/Config.in \
	package/beecrypt/Config.in \
	package/at/Config.in \
	package/pcre/Config.in \
	package/valgrind/Config.in \
	package/readline/Config.in \
	package/pkg-config/Config.in \
	package/oprofile/Config.in \
	package/mpatrol/Config.in \
	package/m4/Config.in \
	package/libtool/Config.in \
	package/mpfr/Config.in \
	package/gperf/Config.in \
	package/gmp/Config.in \
	package/gettext/Config.in \
	package/fakeroot/Config.in \
	package/dmalloc/Config.in \
	package/distcc/Config.in \
	package/cvs/Config.in \
	toolchain/ccache/Config.in.2 \
	package/bison/Config.in \
	package/automake/Config.in \
	package/autoconf/Config.in \
	package/tar/Config.in \
	package/sed/Config.in \
	package/patch/Config.in \
	package/make/Config.in \
	package/grep/Config.in \
	toolchain/gcc/Config.in.2 \
	package/gawk/Config.in \
	package/flex/Config.in \
	package/findutils/Config.in \
	package/diffutils/Config.in \
	package/coreutils/Config.in \
	package/bzip2/Config.in \
	package/bash/Config.in \
	package/busybox/Config.in \
	package/Config.in \
	toolchain/external-toolchain/Config.in.2 \
	toolchain/sstrip/Config.in \
	toolchain/mklibs/Config.in \
	toolchain/elf2flt/Config.in \
	toolchain/Config.in.2 \
	toolchain/gdb/Config.in \
	toolchain/external-toolchain/Config.in \
	toolchain/ccache/Config.in \
	toolchain/gcc/Config.in \
	toolchain/binutils/Config.in \
	toolchain/uClibc/Config.in \
	toolchain/kernel-headers/Config.in \
	toolchain/Config.in.1 \
	target/device/Config.in.toolchain \
	toolchain/Config.in \
	package/gnuconfig/Config.in \
	target/device/Atmel/Config.in.mirrors \
	target/device/Config.in.mirrors \
	target/generic/Config.in \
	target/device/xtensa/Config.in \
	target/device/x86/Config.in \
	target/device/valka/Config.in \
	target/device/KwikByte/Config.in \
	target/device/Atmel/at91bootstrap/Config.in \
	target/device/Atmel/DataFlashBoot/Config.in \
	target/device/Atmel/AVR32_Config.in \
	target/device/Atmel/AT91_Config.in \
	target/device/Atmel/Config.in \
	target/device/ARMLTD/Config.in \
	target/device/AMD/Config.in \
	project/Config.in \
	target/device/Config.in \
	target/Config.in.arch \
	Config.in

package/config/buildroot-config/auto.conf: \
	$(deps_config)


$(deps_config): ;
