#!/bin/sh

#set -x

NAME=dbus-daemon
NAME2=dbus-uuidgen
NEED_ALTF_DIR=1

RC_USER=dbus
RC_USERN=6
RC_GROUP=sys
RC_GROUPN=3
RC_DESC="DBUS daemon"

. /etc/init.d/common

DBUS_DIRS="/var/lib/dbus /var/run/dbus /var/lock/subsys /tmp/dbus
/etc/dbus-1/system.d /etc/dbus-1/session.d /usr/libexec/dbus-1 
/usr/share/dbus-1/services /usr/share/dbus-1/system-services"

for i in $DBUS_DIRS; do
	if ! test -d $i; then mkdir -p $i; fi
done

PIDFILE=/var/run/messagebus.pid

RETVAL=0

istart() {
	start $NAME2 -- --ensure
	RC_PIDFILE=$PIDFILE start $NAME -- --system
	RETVAL=$?
	if test $RETVAL -eq 0; then touch /var/lock/subsys/dbus-daemon; fi
}

istop() {
	## we don't want to kill all the per-user $processname, we want
	## to use the pid file *only*; because we use the fake nonexistent 
	## program name "$servicename" that should be safe-ish
	RC_PIDFILE=$PIDFILE stop $NAME
	RETVAL=$?
	if test $RETVAL -eq 0; then rm -f /var/lock/subsys/dbus-daemon; fi
}

check_user /var/lib/$RC_USER

case "$1" in
	start) istart ;;
	stop) istop ;;
	status) status $NAME; RETVAL=$? ;;
	restart) restart $NAME; RETVAL=$? ;;
	*) echo $"Usage: $0 {start|stop|status|restart}";;
esac
exit $RETVAL
