#!/bin/sh

DESC="Dynamic DNS update daemon"
TYPE=net

NAME=inadyn-mt

RC_PIDFILE=/var/run/$NAME.pid
RC_MAKE_PID=yes
RC_START_BG=yes

DDNS_CONF=/etc/inadyn.conf
DDNS_CACHE=/var/cache/ddns

. /etc/init.d/common

mkdir -p $DDNS_CACHE

case "$1" in
	start)
		if ! test -f $DDNS_CONF; then
			echo "Starting $NAME: No $DDNS_CONF configuration file, exiting."
			exit 1
		fi
		start $NAME -- --input_file $DDNS_CONF
		;;
	stop) stop $NAME ;;
	status) status $NAME ;;
	restart) restart $NAME ;;
	*) usage $0 "start|stop|status|restart" ;;
esac

