#!/bin/sh
#
# avahi-daemon init script, no support for avahi-autpip or avahi-dnsconfd

#set -x

DESC="The Avahi mDNS/DNS-SD daemon"
NAME=avahi-daemon
TYPE=net
NEED_ALTF_DIR=1
AVAHI_OPTS="-D"

RC_USER=avahi
RC_USERN=68
RC_GROUP=avahi
RC_GROUPN=68
RC_DESC="avahi daemon"

CONF_AVAHI=/etc/avahi

REQUIRE="dbus"

. /etc/init.d/common

# register all running services
# when a new service is started its own initscript or the daemon registers itself
istart() {
	if status $NAME >/dev/null ; then # already running, fake start
		echo "Starting $NAME: OK."
		return 0
	fi
	ntout=$(netstat -ln 2> /dev/null)

	for i in $(ls $CONF_AVAHI/services/* 2> /dev/null); do
		srv=$(basename $i)
		srvn=${srv%.*}
		pt=$(sed -n '\|<type>.*</type>|{n;s|.*<port>\(.*\)</port>|\1|p}' $i)
		if test -z "$pt" -o "$pt" = 0; then continue; fi
		if echo "$ntout" | grep -q ":$pt "; then
			avahi add $srvn 
		else
			avahi remove $srvn
		fi
	done

	start $NAME -- $AVAHI_OPTS
}

# de-register all running services
# when a service is stoped its own initscript or the daemon de-registers itself
istop() {
	stop $NAME
	for i in $(ls $CONF_AVAHI/services/*.service 2> /dev/null); do
		srv=$(basename $i)
		avahi remove ${srv%.*}
	done
}

check_user /var/lib/$RC_USER $CONF_AVAHI

case "$1" in
	start) istart ;; 
	stop) istop ;;
	status) status $NAME ;;
	reload) reload $NAME ;;
	restart) restart $NAME ;;
	*)  usage $0 "start|stop|status|restart|reload" ;;
esac
