#!/bin/sh

DESC="Secure Administrative HTTPS server"
NAME=stunnel
TYPE=net

INETD_CONF=/etc/inetd.conf

STUNNEL_CERT=/etc/ssl/certs/stunnel.pem
BOX_PEM=/etc/ssl/certs/server.pem

. /etc/init.d/common

sinit() {
	if ! test -e $STUNNEL_CERT; then
		ln $BOX_PEM $STUNNEL_CERT
	fi
}

if test "$1" = "init"; then
	sinit
	exit
fi

if check_inetd https || check_inetd swats; then
	exit 2
fi

case "$1" in
	start)
		sinit
		avahi add https
		avahi add swats
		start $NAME
		;;
	stop)
		avahi remove https
		avahi remove swats
		stop $NAME
		;;
	status)	status $NAME ;;
	reload) reload $NAME ;;
	restart) restart $NAME ;;
	*)  usage $0 "start|stop|status|restart|reload|init" ;;
esac
