#!/bin/sh
#
# Start telnet....
#

DESC="Telnet Daemon"
NAME=telnetd
TELNETD_ARGS=-F

INETD_CONF=/etc/inetd.conf

. /etc/init.d/common

if check_inetd telnet; then
	exit 2
fi

[ -r /etc/default/telnet ] && . /etc/default/telnet

istart() {
      start $NAME -- $TELNETD_ARGS
}

istop() {
	printf "Stopping telnetd: "
	stop $NAME
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}

case "$1" in
    start)
	istart
	;;
    stop)
	istop
	;;
    restart|reload)
	restart $NAME
	;;
    *) usage $0 "start|stop|status|restart|reload" ;;
esac
