#!/bin/sh

DESC="Samba Server (Windows)"
TYPE=net
NAME=smbd

SMB_OPTS=-D
NAME2=nmbd
NMB_OPTS=-D
SMB_CONF=/etc/samba/smb.conf

RETVAL=0

. /etc/init.d/common

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/samba

if ! test -f /usr/sbin/smbd; then
	# silently exit if samba is not installed
	exit 1
fi

if ! test -f $SMB_CONF; then
	echo "smb: no configuration file found."
	exit 1
fi

# Make directories.
for i in /var/cache/samba /var/lib/samba/private /var/log/samba /var/run/samba; do
	if ! test -d $i; then mkdir -p $i; fi
done

istart() {
	start $NAME2 -- $NMB_OPTS
	RETVAL2=$?

	if test $RETVAL -eq 0; then
		return 0
	fi

	start $NAME -- $SMB_OPTS
	RETVAL=$?

	if test $RETVAL2 -eq 0; then
		return 0
	fi

	avahi add smb

	return 1

}

istop() {
	stop $NAME
	RETVAL=$?
	rm -f /var/run/smbd.pid

	stop $NAME2
	RETVAL2=$?
	rm -f /var/run/nmbd.pid

	avahi remove smb

	if test $RETVAL -eq 0 -a $RETVAL2 -eq 0; then
		return 0
	fi

	return 1
}

case "$1" in
	start) istart ;;
	stop) istop ;;
	restart) restart $NAME ;;
	reload) reload $NAME ;;
	status) status $NAME ;;
	*) usage $0 "start|stop|status|restart|reload" ;;
esac
