#!/bin/sh

NAME=gerbera
DESC="gerbera provides an A/V UPnP service"
TYPE=user
NEED_ALTF_DIR=1

RC_PIDFILE=/var/run/$NAME.pid
RC_MAKE_PID=yes
RC_START_BG=yes

RC_USER=gerbera
RC_USERN=31
RC_GROUP=multimedia
RC_GROUPN=80
RC_DESC="gerbera daemon"

GB_LOGFILE=/var/log/gerbera.log

GB_HOME=/var/lib
GB_DIR=$NAME
GB_CFG=/etc/gerbera/config.xml

GB_PORT=49152

GB_ARGS="-c $GB_CFG -l $GB_LOGFILE -m $GB_HOME -f $GB_DIR -p $GB_PORT -e eth0"

. /etc/init.d/common

if ! test -f $RC_PIDFILE; then touch $RC_PIDFILE; fi

check_user $GB_HOME/$NAME $RC_PIDFILE

if ! test -e $GB_CFG; then
	gerbera $GB_ARGS
	sleep 2
	kill $(top -n 1 | grep $NAME | cut -d ' ' -f 1) 2> /dev/null
	for i in $(seq 0 60); do
		if ! kill -0 $(top -n 1 | grep $NAME | cut -d ' ' -f 1) 2> /dev/null; then break; fi
		usleep 100000
	done

	# add holder for shares
	sed -i '/<import hidden-files/a \
    	<autoscan> \
        	<directory location="/Public" mode="inotify" recursive="yes"/> \
	    </autoscan> \
    	<filesystem-charset>UTF-8</filesystem-charset> \
	    <metadata-charset>UTF-8</metadata-charset> \
	<playlist-charset>UTF-8</playlist-charset> ' $GB_CFG
fi

case "$1" in
  start)
	# Applying multicast settings to eth0
	route add -net 239.0.0.0 netmask 255.0.0.0 eth0
	ifconfig eth0 allmulti
	start $NAME -- $GB_ARGS
	;;
  stop)
	stop $NAME
	ifconfig eth0 -allmulti
	route del -net 239.0.0.0 netmask 255.0.0.0 eth0
	;;
  reload) reload $NAME ;;
  restart) restart $NAME ;;
  status) status $NAME ;;
  *) usage $0 "start|stop|status|restart|reload" ;;
esac
