#!/bin/sh

DESC="CouchPotato searches and manages your movies"
NAME=couchpotato2
TYPE=user
NEED_ALTF_DIR=1

RC_USER=couchpotato2
RC_USERN=22
RC_GROUP=TV
RC_GROUPN=200
RC_DESC="CouchPotato2 user"

DATA_DIR=/var/lib/couchpotato2
PROG_DIR=/opt/CouchPotato2
PROG=${PROG_DIR}/CouchPotato.py
CONFF=/etc/couchpotato2.conf

PID_DIR=/var/run/couchpotato2
RC_PIDFILE=$PID_DIR/couchpotato2.pid

OPTS="--quiet --daemon --config_file=$CONFF --pid_file=$RC_PIDFILE"

DL_DIR=$(sed -n 's/^to[[:space:]]*=[[:space:]]*\(.*\)/\1/p' $CONFF)

. /etc/init.d/common

if test "$(basename $DL_DIR)" = "Public"; then
	check_user $PROG_DIR $CONFF
	echo "Fail: you have to configure CouchPotato2 first."
	exit 1
fi

for i in $PID_DIR "$DL_DIR"; do
	if ! test -d "$i"; then mkdir -p "$i"; fi
done

if ! test -h /var/log/couchpotato2.log; then
    ln -sf $DATA_DIR/logs/CouchPotato.log /var/log/couchpotato2.log
fi

chmod g+rwxs "$DL_DIR"

check_user $PROG_DIR $PID_DIR $CONFF "$DL_DIR"

case "$1" in
	start) start $PROG --chuid $RC_USER:$RC_GROUP -- $OPTS ;;
	stop) stop $NAME ;;
	status) status $NAME ;;
	restart) restart $NAME ;;
	*) usage $0 "start|stop|status|restart" ;;
esac
