#!/bin/sh

DESC="RSS downloader that grabs your favorite Transmission torrents"
NAME=automatic
TYPE=user
NEED_ALTF_DIR=1

REQUIRE="transmission"

RC_USER=automatic
RC_USERN=17
RC_GROUP=network
RC_GROUPN=81
RC_DESC="Automatic daemon"

AUTOMATIC_DIR=/var/lib/$NAME
AUTOMATIC_STATE=$AUTOMATIC_DIR/automatic.state
AUTOMATIC_OPTS="--logfile /var/log/automatic.log"

. /etc/init.d/common

if ! test -d $AUTOMATIC_DIR; then mkdir -p $AUTOMATIC_DIR; fi
if ! test -f $AUTOMATIC_STATE; then touch $AUTOMATIC_STATE; fi

check_user $AUTOMATIC_DIR

case "$1" in
	start) start $NAME -- $AUTOMATIC_OPTS ;;
	stop) stop $NAME ;;
	status)	status $NAME ;;
	restart) restart $NAME ;;
	*)  usage $0 "start|stop|status|restart" ;;
esac
