#!/bin/sh

case "$1" in
	start)
		for i in $(ls /etc/init.d/S*) ;do
			if ! test -x "$i"; then continue; fi
			logger -s "$($i start)"
		done
		;;

	stop)
		for i in $(ls -r /etc/init.d/S*) ;do
			bn=$(basename $i); nm=rc${bn:3}
			# don't allow inetd, stunnel or httpd to be stopped, or webUI will stop working
			if test "$nm" = "rcsysctrl" -o "$nm" = "rcinetd" -o "$nm" = "rcstunnel" -o "$nm" = "rchttp"; then continue; fi
			if $nm status >& /dev/null; then
				logger -s $($nm stop)
			fi
		done
		;;

	restart)
		lst=""
		for i in $(ls -r /etc/init.d/S*) ;do
			bn=$(basename $i); nm=rc${bn:3}
			if $nm status >& /dev/null; then
				lst="$nm $lst"
				logger -s "$($nm stop)"
			fi
		done
		sleep 3
		for i in $lst; do
			logger -s "$($i start)"
		done
		;;

	status)
		for i in $(ls -r /etc/init.d/S*) ;do
			bn=$(basename $i); nm=rc${bn:3}
			logger -s "$($nm status)"
		done
		;;

	*)
		echo "Usage: $0 {start|stop|restart|status}" >&2
		exit 1
		;;
esac
