#!/bin/sh

case "$1" in
	start)
		for i in /etc/init.d/S* ;do		
			 # Ignore dangling symlinks and non executable files
			if test ! -f "$i" -o ! -x "$i"; then continue; fi
			logger -s "$($i start)"
		done
		;;

	stop)
		for i in $(ls -r /etc/init.d/S*) ;do
			 # dont ignore non executable files, in case user has started them manually
			if test ! -f "$i"; then continue; fi
			bn=$(basename $i)
			nm=${bn:3}
			if test "$nm" = "inetd" -o "$nm" = "sysctrl" -o "$nm" = "syslog"; then continue; fi
			logger -s "$(/bin/sh $i stop)"
		done
		;;

	restart)
		lst=""
		for i in $(ls -r /etc/init.d/S*) ;do
			if test ! -f "$i"; then continue; fi		
			if /bin/sh $i status >& /dev/null; then
				lst="$i $lst"
				logger -s "$(/bin/sh $i stop)"
			fi
		done
		for i in $lst; do
			logger -s "$(/bin/sh $i start)"
		done
		;;

	*)
		echo "Usage: $0 {start|stop|restart}" >&2
		exit 1
		;;
esac
