#!/bin/sh

logger "rcE: Starting reboot/shutdown"
# Stop all executable init scripts in /etc/init.d
# executing them in reverse numerical order.
/etc/init.d/rcall rstop

# wait for services to stop
sleep 5

# force kill resilient processes
killall5 -KILL

sleep 1

# umount attached disks/partitions, simulating kernel hotplug events
# hot.sh removes branch from aufs (if dir /Alt-F belongs to device)

for i in /dev/sd[a-z]; do
  if test -b $i; then
	eject $(basename $i)
  fi
done

# write system time to RTC, waiting for second change
i=0; o="$(date +%s)"
while test "$o" = "$(date +%s)" -a "$i" -lt 200; do i=$((i+1)); done
hwclock -wu

ifconfig eth0 down

mount / -o remount,ro

# do a kexec to a new kernel/rootfs instead of a reboot
if test -f /root/zImage; then
	cd /root

	initrfs=$(ls rootfs.arm.cpio*)
	if test -f "$initrfs"; then 	# make sure that only one exists
		kexec -l zImage --command-line="console=ttyS0,115200" \
			--initrd="$initrfs" && kexec -e
	fi
fi
