#! /bin/sh
#
# urandom: This script saves the random seed between reboots.

NAME=urandom
TYPE=required

RDIR=/var/lib/misc
RFILE=$RDIR/random-seed

. $(dirname $0)/common

if ! test -d $RDIR; then mkdir -p $RDIR; fi

case "$1" in
	start)
		echo -n "Starting $NAME: "
		# Load and then save 512 bytes, which is the size of the entropy pool
		if test -f $RFILE; then
			cat $RFILE >/dev/urandom
		fi

		rm -f $RFILE
		dd if=/dev/urandom of=$RFILE count=1 >& /dev/null
		chmod og-rwx $RFILE
		echo "OK."
		;;

	stop)
		echo -n "Stopping $NAME: "
		# Carry a random seed from shut-down to start-up;
		dd if=/dev/urandom of=$RFILE count=1 >& /dev/null
		chmod og-rwx $RFILE
		echo "OK."
		;;

	status) status $NAME ;;

	*)  usage $0 "start|stop|status" ;;
esac
