#! /bin/sh
#
# urandom	This script saves the random seed between reboots.
#		It is called from the boot, halt and reboot scripts.
#
# Version:	@(#)urandom  1.33  22-Jun-1998  miquels@cistron.nl

NAME=urandom
RFILE=/var/lib/misc/random-seed

. $(dirname $0)/common

case "$1" in
	start)
		echo -n "Starting $NAME: "
		# Load and then save 512 bytes,
		# which is the size of the entropy pool
		if test -f $RFILE; then
			cat $RFILE >/dev/urandom
		fi

		rm -f $RFILE
		dd if=/dev/urandom of=$RFILE count=1 >& /dev/null
		chmod og-rwx $RFILE
		echo "OK."
		;;
		
	stop)
		echo -n "Stopping $NAME: "
		# Carry a random seed from shut-down to start-up;
		# see documentation in linux/drivers/char/random.c
		# Saving random seed
		dd if=/dev/urandom of=$RFILE count=1 >& /dev/null
		chmod og-rwx $RFILE
		echo "OK."
		;;

	status)
		status $NAME
		;;
		
	*)  usage $0 "start|stop|status" ;;
esac
