#! /bin/sh

DESC="Daemon to execute scheduled commands"
NAME=crond
TYPE=sys

. $(dirname $0)/common 

CROND=/var/spool/cron/crontabs
SETF=/tmp/settings_saved

sinit() {
	if ! test -e $CROND; then
		mkdir -p $CROND
	fi
	if ! test -e $CROND/root; then
		touch -r $SETF $CROND/root
	fi
}

case "$1" in
	start) sinit; start $NAME ;;
	stop) stop $NAME ;;
	status)	status $NAME ;;
	restart) restart $NAME ;;
	init) sinit ;;
	*) usage $0 "start|stop|status|restart|init" ;;
esac
