#! /bin/sh

DESC="SMART Disk Monitoring Daemon"
NAME=smartd
TYPE=sys
CONFM=/etc/misc.conf

. /etc/init.d/common

case "$1" in
	start)
		if test -e $CONFM; then
			. $CONFM
		fi

		if test -z "$SMARTD_INTERVAL"; then
			SMARTD_INTERVAL=1800
		else
			SMARTD_INTERVAL=$(expr $SMARTD_INTERVAL \* 60)
		fi

		#start-stop-daemon -S -q -b -x $NAME -- -i $SMARTD_INTERVAL 
		#omsg $?
		start $NAME -- -i $SMARTD_INTERVAL
		;;
	stop) stop $NAME ;;
	status)	status $NAME ;;
	reload)	reload $NAME ;;
	restart) restart $NAME ;;
	*) usage $0 "start|stop|status|restart|reload" ;;
esac
