#! /bin/sh

set -e

DESC="SMART Disk Monitoring Daemon"
NAME=smartd
TYPE=sys
INTERVAL=5400

status() {
	if start-stop-daemon -K -t -q -n $NAME; then
		echo "$NAME running"
		return 0
	else
		echo "$NAME stopped"
		return 1
	fi
}

case "$1" in
	start)
		echo -n "Starting $NAME: "
		start-stop-daemon -S -q -b -x $NAME -- -i $INTERVAL 
		# -p /tmp/smartd.pid -q never
		echo "OK"
		;;
	stop)
		echo -n "Stopping $NAME: "
		start-stop-daemon -K -q -x $NAME
		echo "OK"
		;;
	status)
		status
		;;
	restart|force-reload)
		echo "Restarting $NAME: "
		sh $0 stop
		sleep 1
		sh $0 start
		echo ""
		;;
	*)
		echo "Usage: $0 {start|stop|status|restart|force-reload}" >&2
		exit 1
		;;
esac

exit 0
