#! /bin/sh

DESC="Backup Service"
TYPE=sys
NAME=backup
#REQUIRE="cron" does not works here

CONF=/etc/backup.conf
CRONF=/var/spool/cron/crontabs/root

. /etc/init.d/common

istatus() {
	if ! rccron status >& /dev/null; then
		echo "$1 stopped"
		return 1
	fi
	
	if crontab -l 2>/dev/null | grep -q /usr/bin/backup; then
		echo "$1 running"
		return 0
	else
		echo "$1 stopped"
		return 1
	fi
}

# clean cron backup entries, even if cron is currently stopped
istop() {
	echo -n "Stopping $1: "
	TF=$(mktemp -t)
	crontab -l > $TF 2> /dev/null
	sed -i '\|/usr/bin/backup|d' $TF
	touch -r $CRONF $TF
	crontab $TF 2> /dev/null
	touch -r $TF $CRONF

	rm $TF
	echo "OK."
}

istart() {
	if ! test -f $CONF; then
		echo "$0: no configuration file, exiting"
		return 1
	fi

	require $NAME cron
	echo -n "Starting $1: "
	TF=$(mktemp -t)
	crontab -l > $TF 2> /dev/null
	sed -i '\|/usr/bin/backup|d' $TF

	IFS=";"
	while read id type runas host mac srcpath dstpath when at log rest; do
		if test -z "$id" -o -z "$type" -o -z "$runas" -o -z "$srcpath" \
			-o -z "$dstpath" -o -z "$when" -o -z "$at" -o -z "$log"; then continue; fi
		if test "${id:0:1}" = "#"; then continue; fi
		if test "${when:0:1}" = "d"; then
			mday=${when:1}
			when='*'
		else
			mday='*'
		fi
		echo "0 $at $mday * $when /usr/bin/backup $id #!# Alt-F cron" >> $TF
	done < $CONF

	touch -r $CRONF $TF
	crontab $TF 2> /dev/null
	touch -r $TF $CRONF
	rm $TF

	echo "OK."
}

case "$1" in
	start) istart $NAME ;;
	stop) istop $NAME;;
	restart|reload) restart $NAME ;;
	status) istatus $NAME ;;
	*) usage $0 "start|stop|status|restart|reload" ;;
esac
