#!/bin/sh

DESC="Secure administrative web pages (https)"
NAME=stunnel
#TYPE=net

INETD_CONF=/etc/inetd.conf

STUNNEL_CERT=/etc/ssl/certs/stunnel.pem
BOX_PEM=/etc/ssl/certs/server.pem

. $(dirname $0)/common

istart() {
	if ! test -e $STUNNEL_CERT; then
		ln $BOX_PEM $STUNNEL_CERT
	fi
}

case "$1" in
	init) istart ;;
	start)
		istart
		if grep -qE '(^https|^swats)' $INETD_CONF; then
			echo "$NAME: https and/or swats are already configured through inetd, exiting."
			exit 1
		fi

		start $NAME
		;;
	stop)	stop $NAME ;;
	status)	status $NAME ;;
	reload) reload $NAME ;;
	restart) restart $NAME ;;
	*)  usage $0 "start|stop|status|restart|reload|init" ;;
esac
