#!/bin/sh

DESC="Provides secure administrative web pages"
NAME=stunnel
#TYPE=net
REQUIRE="inetd"
INETD_CONF=/etc/inetd.conf

. $(dirname $0)/common

istart() {
	rcvsftpd init

	if grep -qE '(^https|^swats)' $INETD_CONF; then
		echo "$NAME: https and/or swats are already configured through inetd, exiting."
		exit 0
	fi

	start $NAME
}

case "$1" in
	start) istart ;;
	stop)	stop $NAME ;;
	status)	status $NAME ;;
	reload) reload $NAME ;;
	restart) restart $NAME ;;
	*)  usage $0 "start|stop|status|restart|reload" ;;
esac
