#! /bin/sh

DESC="The Common Unix Printing System daemon"
TYPE=sys
NAME=cupsd

PRINTC=/etc/printcap
NEED_ALTF_DIR=1

BOX_CRT=/etc/ssl/certs/server.crt
BOX_KEY=/etc/ssl/certs/server.key

CUPS_CRT=/etc/ssl/certs/cups.crt
CUPS_KEY=/etc/ssl/certs/cups.key

CUPS_CONF=/etc/cups

RC_USER=cups
RC_USERN=9
RC_GROUP=lpadmin
RC_GROUPN=9
RC_DESC="CUPS Daemon"

. /etc/init.d/common

if ! test -e $CUPS_CRT; then
	ln -sf $BOX_CRT $CUPS_CRT                                            
	ln -sf $BOX_KEY $CUPS_KEY   
fi

CUPS_DIRS="/var/spool/cups /var/cache/cups /var/run/cups /var/log/cups"
for i in $CUPS_DIRS; do
	if ! test -d $i; then mkdir -p $i; fi
done

check_user $CUPS_CONF $CUPS_DIRS

# FIXME
chmod a+rx /usr/sbin/cupsd

case "$1" in
	start)
		export TZ=$(cat /etc/TZ)
		unset TMPDIR

		rcinetd disable printer
		start $NAME
		avahi add ipp

		for i in $(seq 0 100); do
			usleep 100000
			if cupsctl >& /dev/null; then
				cupsctl _remote_admin=1 _share_printers=1 >& /dev/null
				break
			fi
		done
		;;

	stop)
		stop $NAME

		# allow empty printcap
		if grep -q cupsd $PRINTC >& /dev/null; then 
			echo -n > $PRINTC
		fi		

		rcinetd enable printer
		avahi remove ipp
		;;

	restart) restart $NAME ;;
	reload) reload $NAME ;;
	status) status $NAME ;;
	*) usage $0 "start|stop|status|restart|reload|init" ;;
esac
