#! /bin/sh

DESC="The Common Unix Printing System daemon"
TYPE=sys
NAME=cupsd
INETD_CONF=/etc/inetd.conf
PRINTC=/etc/printcap

BOX_CRT=/etc/ssl/certs/server.crt
BOX_KEY=/etc/ssl/certs/server.key

CUPS_CRT=/etc/cups/ssl/server.crt
CUPS_KEY=/etc/cups/ssl/server.key

CUPS_USER=cups
CUPS_GROUP=lpadmin

. $(dirname $0)/common

sinit() {
	if ! test -e $CUPS_CRT; then
		cp $BOX_CRT $CUPS_CRT                                            
		cp $BOX_KEY $CUPS_KEY   
	fi
}

case "$1" in
	init) sinit ;;
	start)
		sinit
		export TZ=$(cat /etc/TZ)
		unset TMPDIR

		rcinetd disable printer
		start $NAME
		avahi add ipp

		while ! cupsctl >& /dev/null ; do usleep 100000; done
		cupsctl _remote_admin=1 _share_printers=1 >& /dev/null
		;;

	stop)
		stop $NAME

		# allow empty printcap
		if grep -q cupsd $PRINTC >& /dev/null; then 
			#rm $PRINTC
			echo -n > $PRINTC
		fi		

		rcinetd enable printer
		avahi remove ipp
		;;

	restart) restart $NAME ;;
	reload) reload $NAME ;;
	status) status $NAME ;;
	*) usage $0 "start|stop|status|restart|reload|init" ;;
esac
