#! /bin/sh
#
# System-V init script for the openntp daemon
#

DESC="Network Time Protocol Daemon"
TYPE=net
NAME=ntpd
#REQUIRE="cron" does not works here.

CONF=/etc/ntp.conf
CONFM=/etc/misc.conf
NTPD_CRON=/tmp/ntpd.cron
CRONF=/var/spool/cron/crontabs/root

. $(dirname $0)/common

if test -e $CONFM; then
	. $CONFM
fi

istatus() {
	if status $1 >& /dev/null; then
		echo "$1 running"
		return 0
	else
		crontab -l 2>/dev/null | grep -q adjtime 
		if test $? = 0; then
			echo "$1 running"
			return 0
		else
			echo "$1 stopped"
			return 1
		fi
	fi
}

update_cron() {
	crontab -l > $NTPD_CRON 2> /dev/null
	if test $? = 1 -a $# = 0 ; then return; fi

	sed -i '\|/usr/sbin/adjtime|d' $NTPD_CRON

	if test $# = 1; then
		echo "$1" >> $NTPD_CRON
	fi
	touch -r $CRONF $NTPD_CRON
	crontab $NTPD_CRON
	touch -r $NTPD_CRON $CRONF
	rm $NTPD_CRON
}

get_server() {
	while read arg server; do
		if test "$arg" = "server" -a "$server" != "127.127.1.0"; then
			echo $server
			return
		fi
	done < $CONF
}

case "$1" in
	start)
		if test "$NTPD_DAEMON" = "yes" ; then
			if test "$NTPD_BOOT" = "yes" ; then
				echo -n "$NAME: Getting initial time via ntp: "
				#ntpd -qg
				sntp -t 2 -s $(get_server) >& /dev/null
				omsg $?
			fi

			echo -n "Starting $NAME: "
			update_cron
			avahi add ntp
			adjtimex -f 0 >& /dev/null # if != 0 affects ntpd drift calculation 
			start-stop-daemon -S -q -x $NAME
		else
			require $NAME cron
			echo -n "$NAME: Setting up crontab... "
			adjtime -restart >& /dev/null
			update_cron "0 6 * * * /usr/sbin/adjtime -adjust #!# Alt-F cron"
		fi
		omsg $?
		;;

	stop) stop $NAME
		avahi remove ntp
		update_cron
		;;
	restart) restart $NAME ;;
	status) istatus $NAME ;;
	*) usage $0 "start|stop|status|restart" ;;
esac
