#!/bin/sh

DESC="Dynamic DNS update daemon"
TYPE=net

NAME=inadyn
if test -x /usr/bin/inadyn-mt; then
	NAME=inadyn-mt
fi

CONF=/etc/inadyn.conf

RC_PIDFILE=/var/run/$NAME.pid
RC_MAKE_PID=yes
RC_START_BG=yes

. /etc/init.d/common

case "$1" in
	start)
		if ! test -f $CONF; then
			echo "Starting $NAME: No $CONF configuration file, exiting."
			exit 1
		fi
		start $NAME
		;;
	stop) stop $NAME ;;
	status) status $NAME ;;
	restart) restart $NAME ;;
	*) usage $0 "start|stop|status|restart" ;;
esac

