#!/bin/sh
#
# avahi-daemon init script, no support for avahi-autpip or avahi-dnsconfd

#set -x

DESC="The Avahi mDNS/DNS-SD daemon"
NAME=avahi-daemon
TYPE=net
NEED_ALTF_DIR=1
AVAHI_OPTS="-D"

RC_USER=avahi
RC_USERN=68
RC_GROUP=avahi
RC_GROUPN=68
RC_DESC="avahi daemon"

CONF_AVAHI=/etc/avahi

REQUIRE="dbus"

. /etc/init.d/common

# register all running services
# when a new service is started its own initscript or the daemon registers itself
istart() {
	if status $NAME >/dev/null ; then # already running, fake start
		echo "Starting $NAME: OK."
		return 0
	fi
	ntout=$(netstat -ln 2> /dev/null)

	for i in /etc/avahi/services/*; do
		srv=$(basename $i)
		srvn=${srv%.*}
		pt=$(sed -n '\|<type>_'$srvn'.*</type>|{ns|.*<port>\(.*\)</port>|\1|p}' $i)
		if echo "$ntout" | grep -q ":$pt "; then
			avahi add ${srv%.*} 
		else
			avahi remove ${srv%.*}
		fi
	done

	start $NAME -- $AVAHI_OPTS
}

# de-register all running services
# when a service is stoped its own initscript or the daemon de-registers itself
istop() {
	stop $NAME
	for i in /etc/avahi/services/*.service; do
		srv=$(basename $i)
		avahi remove ${srv%.*}
	done
}

check_user /var/lib/$RC_USER $CONF_AVAHI

case "$1" in
	start) istart ;; 
	stop) istop ;;
	status) status $NAME ;;
	reload) reload $NAME ;;
	restart) restart $NAME ;;
	*)  usage $0 "start|stop|status|restart|reload" ;;
esac
