#!/bin/sh
#
# avahi-daemon init script, no support for avahi-autpip or avahi-dnsconfd

DESC="The Avahi mDNS/DNS-SD daemon"
NAME=avahi-daemon
TYPE=net
AVAHI_OPTS="-D"

REQUIRE="dbus"
REQUIREDBY="forked_daapd afpd"

. $(dirname $0)/common

# register all running services
# when a new service is start its own initscript or the daemon registers itself
istart() {
	if status $NAME >/dev/null ; then # already running, fake start
		echo "Starting $NAME: OK."
		return 0
	fi
	ntout=$(netstat -ln 2> /dev/null)

	for i in /etc/avahi/services/*; do
		pt=$(sed -n 's|.*<port>\(.*\)</port>|\1|p' $i)
		srv=$(basename $i)
		if echo "$ntout" | grep -q ":$pt "; then
			avahi add ${srv%.*} 
		else
			avahi remove ${srv%.*}
		fi
	done

	start $NAME -- $AVAHI_OPTS
}

# de-register all running services
# when a service is stoped its own initscript or the daemon de-registers itself
istop() {
	stop $NAME
	for i in /etc/avahi/services/*.service; do
		srv=$(basename $i)
		avahi remove ${srv%.*}
	done
}

case "$1" in
	start) istart ;; 
	stop) istop ;;
	status) status $NAME ;;
	reload) reload $NAME ;;
	restart) restart $NAME ;;
	*)  usage $0 "start|stop|status|restart|reload" ;;
esac
