#!/bin/sh -e

NAME=afpd
NAME2=cnid_metad
DESC="AppleTalk Filing Protocol daemon."
TYPE=net

AFPD_OPTS="-P /var/run/afpd.pid"
CNID_OPTS="-l log_info"

. $(dirname $0)/common

istart() {
	if ! rcavahi-daemon status > /dev/null; then
		rcavahi-daemon start > /dev/null
	fi
	start $NAME2 -- $CNID_OPTS
	start $NAME -- $AFPD_OPTS
	avahi add afpovertcp
}

istop() {
	avahi remove afpovertcp
	stop $NAME
	stop $NAME2
}

case "$1" in
	start) istart ;;
	stop) istop ;;
	restart) restart $NAME ;;
	reload) reload $NAME ;;
	status) status $NAME ;;

	*)
		echo "Usage: $0 {start|stop|status|restart|reload}"
		exit 1
		;;
esac
