#! /bin/sh

DESC="AFP (Apple Filling Protocol) fileserver"
TYPE=net
NAME=netatalk

REQUIRE=avahi_daemon
NETATALK_CONF=/etc/afp.conf

. $(dirname $0)/common

# the shipped configuration file needs some adjustments

# replace /home by its real path
if rh=$(realpath /home 2>/dev/null); then
	sed -i "s|^[[:space:]]*basedir regex[[:space:]]*=[[:space:]]*/home.*$|\tbasedir regex = $rh|" $NETATALK_CONF
fi

# replace /Public by its real path, or comment it
if rp=$(realpath /Public 2>/dev/null); then
	sed -i "s|^[[:space:]]*path[[:space:]]*=[[:space:]]*/Public/|\tpath = $rp/|" $NETATALK_CONF
else
	sed -i '/^\[Public Read.*\]/,/^$/s/^/#&/' $NETATALK_CONF
fi

# replace /Backup by its real path, or comment it
if rb=$(realpath /Backup 2>/dev/null); then
	sed -i "s|^[[:space:]]*path[[:space:]]*=[[:space:]]*/Backup|\tpath = $rb|" $NETATALK_CONF
	if ! test -d /Backup/TM; then
		mkdir /Backup/TM
		chown backup:backup /Backup/TM
	fi
else
	sed -i '/^\[Backup\]/,/^$/s/^/#&/' $NETATALK_CONF
	sed -i '/^\[Time Machine\]/,/^$/s/^/#&/' $NETATALK_CONF
fi

case "$1" in
	start)	start $NAME	;;
	stop)	stop $NAME ;;
	status)	status $NAME ;;
	restart) restart $NAME ;;
	reload) reload $NAME ;;
	*) usage $0 "start|stop|status|restart|reload" ;;
esac
