#! /bin/sh

DESC="A secure, fast, compliant and very flexible web-server"
TYPE=net
NAME=lighttpd
CONF=/etc/lighttpd/lighttpd.conf
LOG_DIR=/var/log/lighttpd 
HOME_DIR=/var/lib/lighttpd
SECR_DIGST=/etc/lighttpd/lighttpd-digest.user
SECR_RSYNC=/etc/rsyncd.secrets 
LIGHTY_PEM=/etc/ssl/certs/lighttpd.pem
BOX_PEM=/etc/ssl/certs/server.pem

. $(dirname $0)/common

digs_pass() {
	realm="WebDAV"
	while read ln; do
    	user=$(echo $ln | cut -d: -f1)
		pass=$(echo $ln | cut -d: -f2)
		hash=$(echo -n "$user:$realm:$pass" | md5sum | cut -b -32)
		echo "$user:$realm:$hash" 
	done < $SECR_RSYNC
}

istart() {
	if ! test -d $LOG_DIR; then
		mkdir -p $LOG_DIR
		chown lighttpd:network $LOG_DIR
	fi

	if ! test -d $HOME_DIR/sockets; then
		mkdir $HOME_DIR/sockets
		chown lighttpd $HOME_DIR/sockets
	fi

	if test $SECR_RSYNC -nt $SECR_DIGST -o ! -f $SECR_DIGST; then
		digs_pass > $SECR_DIGST
		chown lighttpd $SECR_DIGST
		chmod go-rwx $SECR_DIGST
	fi

	if ! test -e $LIGHTY_PEM; then
		ln $BOX_PEM $LIGHTY_PEM
	fi
}

case "$1" in
	init) istart ;;
	start)
		if ! test -f $CONF; then
			echo "Starting $NAME: No $CONF configuration file, fail"
			exit 1
		fi

		if test "$(sed -n 's|^var.server_root.*=.*"\(.*\)"|\1|p' $CONF)" = "/Public"; then
			echo "$NAME: \"Server Root\" not set, you have to configure $NAME first."
			exit 1
		fi

		istart
		start $NAME -- -f $CONF
		;;
	stop) stop $NAME ;;
	status)	status $NAME ;;
	restart) restart $NAME ;;
	*) usage $0 "start|stop|status|restart|init" ;;
esac

