#! /bin/sh

DESC="A secure, fast, compliant and very flexible web-server"
TYPE=net
NAME=lighttpd
NEED_ALTF_DIR=1

CONF=/etc/$NAME/$NAME.conf
LOG_DIR=/var/log/$NAME 
HOME_DIR=/var/lib/$NAME

SECR_DIGST=/etc/$NAME/lighttpd-digest.user
SECR_RSYNC=/etc/rsyncd.secrets 
VSFTPD_PEM=/etc/ssl/certs/vsftpd.pem
LIGHTY_PEM=/etc/ssl/certs/lighttpd.pem
BOX_PEM=/etc/ssl/certs/server.pem

RC_USER=$NAME
RC_USERN=35
RC_GROUP=network
RC_GROUPN=81
RC_DESC="Lighttpd daemon"

. /etc/init.d/common

if ! test -d $LOG_DIR; then mkdir -p $LOG_DIR; fi
if ! test -d $HOME_DIR/sockets; then mkdir -p $HOME_DIR/sockets; fi

check_user $CONF $LOG_DIR $HOME_DIR

digs_pass() {
	realm="WebDAV"
	while read ln; do
    	user=$(echo $ln | cut -d: -f1)
		pass=$(echo $ln | cut -d: -f2)
		hash=$(echo -n "$user:$realm:$pass" | md5sum | cut -b -32)
		echo "$user:$realm:$hash" 
	done < $SECR_RSYNC
}

istart() {
	if test $SECR_RSYNC -nt $SECR_DIGST -o ! -f $SECR_DIGST; then
		digs_pass > $SECR_DIGST
		chown lighttpd $SECR_DIGST
		chmod go-rwx $SECR_DIGST
	fi

	if ! test -e $BOX_PEM; then
		ln $VSFTPD_PEM $BOX_PEM
	fi

	if ! test -e $LIGHTY_PEM; then
		ln $BOX_PEM $LIGHTY_PEM
	fi
}

case "$1" in
	init) istart ;;
	start)
		if ! test -f $CONF; then
			echo "Starting $NAME: No $CONF configuration file, fail"
			exit 1
		fi

		if test "$(sed -n 's|^var.server_root.*=.*"\(.*\)"|\1|p' $CONF)" = "/Public"; then
			echo "$NAME: \"Server Root\" not set, you have to configure $NAME first."
			exit 1
		fi

		istart
		start $NAME -- -f $CONF
		;;
	stop) stop $NAME ;;
	status)	status $NAME ;;
	restart) restart $NAME ;;
	*) usage $0 "start|stop|status|restart|init" ;;
esac

