#!/bin/sh
#
# nfs           This shell script takes care of starting and stopping
#               the NFS services. Stolen from RedHat FC5.

DESC="Network File System Server (unix)"
TYPE=net
NAME=nfsd

PORTMAP_FLAG=-v

. $(dirname $0)/common

# The /var/lib/nfs directory is actually on a tmpfs filesystem.
# except when Alt-F is aufs mounted (just install ipkg for this to take effect)

mkdir -p /var/lib/nfs/sm /var/lib/nfs/sm.bak

touch /var/lib/nfs/etab /var/lib/nfs/rmtab \
	/var/lib/nfs/state /var/lib/nfs/xtab

chown -R daemon /var/lib/nfs /var/lib/nfs

istart() {
	# Don't fail if /etc/exports doesn't exist;
	# create a bare-bones version and continue.

	if test ! -f /etc/exports; then
		touch /etc/exports
		chmod u+rw,g+r,o+r /etc/exports
		echo "Creating default NFS exports file."
		ip=$(ifconfig eth0 | awk '/inet addr/ { print substr($2, 6) }')
		cnet=$(echo $ip | cut -d. -f1-3).0/24
		options="rw,no_root_squash,no_subtree_check,anonuid=99,anongid=98"

		for f in /mnt/*; do
			if mountpoint -q $f; then
				echo "$f $cnet($options)" >> /etc/exports
			fi
		done
	fi

	if ! test -f /proc/fs/nfsd/exports; then
		mount -t nfsd nfsd /proc/fs/nfsd
	fi

	# portmap fails when starting/stopping it in fast succession.
	# Port 111 stays open in CLOSE_WAIT for 1 minute. Why?
	#
	# oddly, portmap does returns 0 when failing (uclibc bug?)
	# so, check if it started successfuly using rpcinfo to check.
	
	echo -n "Starting portmap: "
	portmap $PORTMAP_FLAG
	sleep 2
	while ! rpcinfo -p >& /dev/null ; do
		portmap $PORTMAP_FLAG
		echo -n .
		sleep 2
	done
	echo "OK."

	exportfs -r
	start rpc.mountd
	start rpc.statd -- --no-notify
	start rpc.nfsd -- -s 2
	start sm-notify
}

istop() {
	stop nfsd 9 # should be 2.
	stop rpc.statd
	stop rpc.mountd
	exportfs -au
	stop portmap
	rm -f /var/run/portmap_mapping /var/run/sm-notify.pid

	if test -f /proc/fs/nfsd/exports; then
		umount /proc/fs/nfsd
		# blocks, as sunrpc modules has refcont = 2, although not in use
		# modprobe -r nfsd 
		rmmod -f nfsd lockd exportfs
	fi
}

case "$1" in
	start) istart ;;
	stop) istop ;;
	status) status $NAME ;;
	restart) restart $NAME ;;
	reload)
		/usr/sbin/exportfs -r
		;;
	*) usage $0 "start|stop|status|restart|reload" ;;
esac
