#!/bin/sh

DESC="Network File System Server (unix)"
TYPE=net
NAME=nfsd
REQUIRE="portmap"

MISCC=/etc/misc.conf

. /etc/init.d/common

if test -f $MISCC; then
	. $MISCC
fi

# The /var/lib/nfs directory is actually on a tmpfs filesystem.
# except when Alt-F is aufs mounted (just install ipkg for this to take effect)

if ! test -d /var/lib/nfs/sm -a -d /var/lib/nfs/sm.bak; then
	mkdir -p /var/lib/nfs/sm /var/lib/nfs/sm.bak
	chown -R daemon /var/lib/nfs
fi

istart() {
	if test -n "$DELAY_NFS"; then
		if ! aufs.sh -s >& /dev/null ; then
			echo "NFS: delaying NFS start"
			return 1
		fi
	fi

	if test -n "$CLEAN_STALE_NFS" -a ! -f /var/lib/nfs/.rmtab.lock; then
		rm -f /var/lib/nfs/rmtab
	fi

	# Don't fail if /etc/exports doesn't exist;
	# create a bare-bones version and continue.

	if test ! -f /etc/exports; then
		touch /etc/exports
		chmod u+rw,g+r,o+r /etc/exports
		echo "Creating default NFS exports file."
		ip=$(ifconfig eth0 | awk '/inet addr/ { print substr($2, 6) }')
		cnet=$(echo $ip | cut -d. -f1-3).0/24
		options="rw,no_root_squash,no_subtree_check,anonuid=99,anongid=98"

		for f in /mnt/*; do
			if mountpoint -q $f; then
				echo "$f $cnet($options)" >> /etc/exports
			fi
		done
	fi

	if ! test -f /proc/fs/nfsd/exports; then
		mount -t nfsd nfsd /proc/fs/nfsd
		sleep 1
		if test -n "$NFS_BLKSIZE"; then
			echo $NFS_BLKSIZE > /proc/fs/nfsd/max_block_size
		fi
	fi

	exportfs -r
	start rpc.mountd -- --no-nfs-version 4
	start rpc.statd -- --no-notify
	start rpc.nfsd -- --no-nfs-version 4 -s 4
	start sm-notify
	avahi add nfs
}

istop() {
	stop nfsd 2

# loaded modules: nfsd exportfs (lockd grace sunrpc are common)

#	if ! rcnfs_client status >& /dev/null; then
	if test -z "$(mount -t nfs)"; then
		stop rpc.statd
		rm -f /var/run/sm-notify.pid
		modprobe -r lockd 2> /dev/null
	fi

	stop rpc.mountd
	exportfs -au
	
	if test -f /proc/fs/nfsd/exports; then
		umount /proc/fs/nfsd
		modprobe -r nfsd 2> /dev/null
	fi

	avahi remove nfs
}

case "$1" in
	start) istart ;;
	stop) istop ;;
	status) status $NAME ;;
	restart) restart $NAME ;;
	reload) /usr/sbin/exportfs -r ;;
	*) usage $0 "start|stop|status|restart|reload" ;;
esac
