#!/bin/sh

DESC="NFS Client"
NAME=rpc.statd
NAME2=sm-notify
REQUIRE="portmap"

PORTMAP_FLAG="" #-v

. /etc/init.d/common

# The /var/lib/nfs directory is actually on a tmpfs filesystem.
# except when Alt-F is aufs mounted (just install ipkg for this to take effect)

mkdir -p /var/lib/nfs/sm /var/lib/nfs/sm.bak

touch /var/lib/nfs/etab /var/lib/nfs/rmtab \
	/var/lib/nfs/state /var/lib/nfs/xtab

chown -R daemon /var/lib/nfs /var/lib/nfs

istart() {
	start $NAME2
	start $NAME -- --no-notify
}

istop() {
	st=0
	echo -n "Stopping $NAME: "
	if test -n "$(mount -t nfs)"; then
		if ! umount -f -t nfs -a >& /dev/null; then
			echo "Fail: Couldn't unmount NFS filesystems and stop nfs-client."
			st=1
		fi
	fi

	# loaded modules: nfsv3 nfsv2 nfs (lockd grace sunrpc are common)
	if ! rcnfs status >& /dev/null; then
		stop $NAME
		rm -f /var/run/sm-notify.pid
		modprobe -r nfsv2 nfsv3 2> /dev/null
		st=0 # return true, as rmmod might fail
	fi
	omsg $st
}

case "$1" in
	start) istart ;;
	stop) istop ;;
	status) status $NAME ;;
	restart) restart $NAME ;;
	*) usage $0 "start|stop|status|restart" ;;
esac
