#!/bin/sh

DESC="NFS Network Status Monitor (unix)"
#TYPE=net
REQUIRE="portmap"

NAME=rpc.statd
NAME2=sm-notify
MISCC=/etc/misc.conf

. /etc/init.d/common

if test -f $MISCC; then
	. $MISCC
fi

istart() {
	if test -n "$DELAY_NFS"; then
		if ! aufs.sh -s >& /dev/null ; then
			echo "NSM: delaying NFS start"
			return 1
		fi
	fi

	echo -n "Starting $NAME: "

	# /var/lib/nfs is actually on a tmpfs filesystem.
	# except when Alt-F is aufs mounted (just install ipkg for this to take effect)
	if ! test -d /var/lib/nfs/sm -a -d /var/lib/nfs/sm.bak; then
		mkdir -p /var/lib/nfs/sm /var/lib/nfs/sm.bak
		chmod 0700 /var/lib/nfs/sm /var/lib/nfs/sm.bak
		chown -R daemon /var/lib/nfs
	fi

	start $NAME2
	start $NAME -- --no-notify

	echo "OK."
}

istop() {
	echo -n "Stopping $NAME: "
	stop $NAME
	rm -f /var/run/sm-notify.pid
	modprobe -r nfsv2 nfsv3 >& /dev/null
	echo "OK."
}

case "$1" in
	start) istart ;;
	stop) istop ;;
	status) status $NAME ;;
	restart) restart $NAME ;;
	*) usage $0 "start|stop|status|restart" ;;
esac
