#!/bin/sh

DESC="NFS (Network File System) Server (unix)"
TYPE=net
NAME=nfsd
REQUIRE="nsm"

MISCC=/etc/misc.conf
FSTABC=/etc/fstab

. /etc/init.d/common

if test -f $MISCC; then
	. $MISCC
fi

# remove possible leftovers from previous firmware 
rm -rf /etc/init.d/S60nfs /etc/init.d/S60nfs_client

istart() {
	if test -n "$DELAY_NFS"; then
		if ! aufs.sh -s >& /dev/null ; then
			echo "NFS server: delaying NFS start"
			return 1
		fi
	fi

	# The /var/lib/nfs directory is actually on a tmpfs filesystem.
	# except when Alt-F is aufs mounted (just install ipkg for this to take effect)
	if ! test -d /var/lib/nfs/sm -a -d /var/lib/nfs/sm.bak; then
		mkdir -p /var/lib/nfs/sm /var/lib/nfs/sm.bak
		chmod 0700 /var/lib/nfs/sm /var/lib/nfs/sm.bak
		chown -R daemon /var/lib/nfs
	fi

	# rpc.mountd man page says that rmtab entries might be innaccurate
	if test -n "$CLEAN_STALE_NFS" -a ! -f /var/lib/nfs/.rmtab.lock; then
		rm -f /var/lib/nfs/rmtab
	fi

	# Don't fail if /etc/exports doesn't exist, create a bare-bones version and continue.
	if ! test -f /etc/exports; then
		touch /etc/exports
		chmod u+rw,g+r,o+r /etc/exports
		echo "Creating default NFS exports file."
		ip=$(ifconfig eth0 | awk '/inet addr/ { print substr($2, 6) }')
		cnet=$(echo $ip | cut -d. -f1-3).0/24
		options="rw,no_root_squash,no_subtree_check,anonuid=99,anongid=98"

		for f in /mnt/*; do
			if mountpoint -q $f; then
				echo "$f $cnet($options)" >> /etc/exports
			fi
		done
	fi

	if ! test -f /proc/fs/nfsd/exports; then
		mount -t nfsd nfsd /proc/fs/nfsd
		sleep 1
		if test -z "$NFS_BLKSIZE"; then
			if test $(awk '/MemTotal/{print $2}' /proc/meminfo) -lt 262144; then
				NFS_BLKSIZE=32768
			fi
		fi
		echo $NFS_BLKSIZE > /proc/fs/nfsd/max_block_size
	fi

	exportfs -r
	start rpc.mountd -- --no-nfs-version 4
	start rpc.nfsd -- --no-nfs-version 4 -s 4
	avahi add nfs

	return 0
}

istop() {
	stop nfsd 2
	stop rpc.mountd
	exportfs -au
	
	if test -f /proc/fs/nfsd/exports; then
		umount /proc/fs/nfsd
		modprobe -r nfsd 2> /dev/null
	fi

	avahi remove nfs
}

case "$1" in
	start) istart ;;
	stop) istop ;;
	status) status $NAME ;;
	restart) restart $NAME ;;
	reload) /usr/sbin/exportfs -r ;;
	*) usage $0 "start|stop|status|restart|reload" ;;
esac
