#!/bin/sh
#
# Stolen from RedHat FC5.
#

DESC="Samba Server (Windows)"
NAME=smbd
TYPE=net
RETVAL=0

# Check that smb.conf exists.
[ -f /etc/samba/smb.conf ] || exit 0

. $(dirname $0)/common

sinit() {
	# Make directories.
	mkdir -p /var/cache/samba
	mkdir -p /var/log/samba
	mkdir -p /var/lock/subsys
}

start() {
	echo -n "Starting NMB services: "
	sinit
	nmbd -D
	RETVAL2=$?
	echo "OK."

	echo -n "Starting SMB services: "
	smbd -D
	RETVAL=$?
	echo "OK."

	[ $RETVAL -eq 0 -a $RETVAL2 -eq 0 ] && touch /var/lock/subsys/smb || \
	   RETVAL=1
	return $RETVAL
}	

stop() {
	echo -n "Shutting down SMB services: "
	start-stop-daemon -K -q -n smbd
	RETVAL=$?
	rm -f /var/run/smbd.pid
	echo "OK."

	echo -n "Shutting down NMB services: "
	start-stop-daemon -K -q -n nmbd
	RETVAL2=$?
	rm -f /var/run/nmbd.pid

	[ $RETVAL -eq 0 -a $RETVAL2 -eq 0 ] && rm -f /var/lock/subsys/smb
	echo "OK."
	return $RETVAL
}	

case "$1" in
	start) start ;;
	stop) stop ;;
	restart) restart $NAME ;;
	reload) reload $NAME ;;
	status) status $NAME ;;
	*) usage $0 "start|stop|status|restart|reload" ;;
esac
