#!/bin/sh

DESC="Samba Server (Windows)"
TYPE=net
NAME=smbd

SMB_OPTS=-D
NAME2=nmbd
NMB_OPTS=-D
SMB_CONF=/etc/samba/smb.conf

RETVAL=0

. /etc/init.d/common

# Check that smb.conf exists.
if ! test -f /etc/samba/smb.conf; then
	echo "smb: no configuration file found."
	exit 1
fi

# Make directories.
for i in /var/cache/samba /var/log/samba /var/lock/subsys; do
	if ! test -d $i; then mkdir -p $i; fi
done

istart() {
	start $NAME2 -- $NMB_OPTS
	RETVAL2=$?

	start $NAME -- $SMB_OPTS
	RETVAL=$?

	avahi add smb

	if test $RETVAL -eq 0 -a $RETVAL2 -eq 0; then
		touch /var/lock/subsys/smb
	else
		RETVAL=1
	fi
	return $RETVAL
}	

istop() {
	stop $NAME
	RETVAL=$?
	rm -f /var/run/smbd.pid

	stop $NAME2
	RETVAL2=$?
	rm -f /var/run/nmbd.pid

	avahi remove smb

	if test $RETVAL -eq 0 -a $RETVAL2 -eq 0; then
		rm -f /var/lock/subsys/smb
	else
		RETVAL=1
	fi
	return $RETVAL
}	

case "$1" in
	start) istart ;;
	stop) istop ;;
	restart) restart $NAME ;;
	reload) reload $NAME ;;
	status) status $NAME ;;
	*) usage $0 "start|stop|status|restart|reload" ;;
esac
