#! /bin/sh

DESC="FTP/FTPS server"
NAME=vsftpd
TYPE=net

CONF=/etc/vsftpd.conf
CONFU=/etc/vsftpd.user_list

BOX_PEM=/etc/ssl/certs/server.pem

RC_PIDDIR=/var/run/vsftpd
FTP_PIDFILE=$RC_PIDDIR/vsftpd-ftp.pid
FTPS_PIDFILE=$RC_PIDDIR/vsftpd-ftps.pid

RC_MAKE_PID=y
RC_START_BG=y

OPTS="/etc/vsftpd.conf -olisten=yes"
FTP_OPTS="-olisten_port=21"
FTPS_OPTS="-olisten_port=990 -oimplicit_ssl=yes"

. /etc/init.d/common

sinit() {
	if test -f $CONF; then
		. $CONF
		if test -n "$secure_chroot_dir" -a ! -d "$secure_chroot_dir"; then
			mkdir -p "$secure_chroot_dir"
		fi
 		if test "$ssl_enable" = "yes" -a -n "$rsa_cert_file" -a ! -e "$rsa_cert_file"; then
			ln $BOX_PEM $rsa_cert_file
			chmod og-r $rsa_cert_file
		fi
		if test "$userlist_enable" = "yes" -a ! -f "$CONFU"; then
			touch $CONFU
		fi
		# to remove after RC5
		if grep -q 'listen=' $CONF; then
			sed -i '/listen=/d' $CONF
		fi
	fi
}

if test "$1" = "init"; then
	sinit
	exit
fi

if check_inetd ftp || check_inetd ftps; then
	exit 2
fi

case "$1" in
	start)
		sinit
		if grep -q 'implicit_ssl=yes' $CONF; then
			RC_PIDFILE=$FTPS_PIDFILE start $NAME -- $OPTS $FTPS_OPTS
			avahi add ftps
		fi
		avahi add ftp
		RC_PIDFILE=$FTP_PIDFILE start $NAME -- $OPTS $FTP_OPTS
		;;
	stop)
		avahi remove ftp
		avahi remove ftps
		RC_PIDFILE=$FTPS_PIDFILE stop $NAME
		RC_PIDFILE=$FTP_PIDFILE stop $NAME
		;;
	status)
		RC_PIDFILE=$FTPS_PIDFILE status $NAME
		RC_PIDFILE=$FTP_PIDFILE status $NAME
		;;
	restart) restart $NAME ;;
	*) usage $0 "start|stop|status|restart|init" ;;
esac
