#! /bin/sh

DESC="FUPPES, the Free UPnP Entertainment Service"
TYPE=user
NAME=fuppesd

LOGDIR=/var/log/fuppes
LOGFILE=$LOGDIR/fuppes.log
FUPPES_DIR=/var/lib/fuppes
FUPPES_DB=$FUPPES_DIR/fuppes.db
FUPPES_CONF=/etc/fuppes
FUPPES_ARGS="--config-dir $FUPPES_CONF --log-file $LOGFILE \
	--database-file $FUPPES_DB --log-level 2"

RC_START_BG=yes

RC_USER=fuppes
RC_USERN=12
RC_GROUP=multimedia
RC_GROUPN=80
RC_DESC="Fuppes user"

. /etc/init.d/common

if ! test -d $LOGDIR; then
	mkdir -p $LOGDIR
fi

check_user $FUPPES_CONF $FUPPES_DIR $LOGDIR 

case "$1" in
	start) start $NAME --chuid $RC_USER:$RC_GROUP -- $FUPPES_ARGS ;;
	stop) stop $NAME 2 ;;
	restart) restart $NAME ;;
	status) status $NAME ;;
	*) usage $0 "start|stop|status|restart" ;;
esac
