#! /bin/sh

DESC="DAAP and RSP media server (iTunes)"
NAME=forked-daapd
TYPE=user
NEED_ALTF_DIR=1

EXCLUDEDBY="mt_daapd"
REQUIRE="avahi_daemon"

RC_USER=daapd
RC_USERN=16
RC_GROUP=multimedia
RC_GROUPN=80
RC_DESC="forked-daapd daemon"

CONF_FORKED=/etc/$NAME.conf

FORKED_LOG=/var/log/$NAME.log
FORKED_OVRW_LOG="yes" # overwrite log file on each start

. /etc/init.d/common

check_user $CONF_FORKED /var/lib/$RC_USER

case "$1" in
	start)
		if test "$FORKED_OVRW_LOG" = "yes"; then rm  -f $FORKED_LOG; fi
		start $NAME -- $OPTS 2> /dev/null
		;;
	stop) stop $NAME ;;
	status) status $NAME ;;
	restart) restart $NAME ;;
	*) usage $0 "start|stop|status|restart" ;;
esac
