#! /bin/sh

DESC="DAAP and RSP media server (iTunes)"
NAME=forked-daapd
TYPE=user
NEED_ALTF_DIR=1

EXCLUDEDBY="mt_daapd"
REQUIRE="avahi_daemon"

CONF_FORKED=/etc/$NAME.conf
LOG_FORKED=/var/log/$NAME
RUN_FORKED=/var/run/$NAME

RC_USER=daapd
RC_USERN=16
RC_GROUP=multimedia
RC_GROUPN=80
RC_DESC="forked-daapd daemon"

RC_PIDFILE=$RUN_FORKED/$NAME.pid

FORKED_LOG=$LOG_FORKED/$NAME.log
FORKED_OVRW_LOG="yes" # overwrite log file on each start

# it has to start in foreground!, so create pid and background it
RC_MAKE_PID=y
RC_START_BG=y
OPTS="-f"

. /etc/init.d/common

mkdir -p $LOG_FORKED $RUN_FORKED

check_user $CONF_FORKED /var/lib/$RC_USER $LOG_FORKED $RUN_FORKED

case "$1" in
	start)
		if test "$FORKED_OVRW_LOG" = "yes"; then rm -f $FORKED_LOG; fi
		start $NAME --chuid $RC_USER:$RC_GROUP -- $OPTS 2> /dev/null
		;;
	stop) stop $NAME ;;
	status) status $NAME ;;
	restart) restart $NAME ;;
	*) usage $0 "start|stop|status|restart" ;;
esac
