#! /bin/sh

DESC="Media server for the Roku SoundBridge and iTunes"
TYPE=user
NAME=mt-daapd

EXCLUDEDBY="forked_daapd"

MTDAAPD_USER=mt-daapd
MTDAAPD_GROUP=multimedia

MTDAAPD_ARGS="-y"

. $(dirname $0)/common

case "$1" in
	start) start $NAME -b -- $MTDAAPD_ARGS ;;
	stop) stop $NAME 2 ;;
	restart) restart $NAME ;;
	status) status $NAME ;;
	*) usage $0 "start|stop|status|restart" ;;
esac
