#!/bin/sh -e

NAME=minidlna
DESC="MiniDLNA is a DLNA/UPnP-AV server."
TYPE=user

CONFF=/etc/$NAME.conf
MINIDLNA_USER=$NAME
MINIDLNA_GROUP=multimedia
MINIDLNA_ARGS=""

. $(dirname $0)/common

check_shares() {
	if test -r "$CONFF"; then
		MDLNA_DIR="$(awk -F= '/^media_dir/{printf "%s;", $2}' $CONFF)"
		OIFS="$IFS"; IFS=";"
		for i in $MDLNA_DIR; do
			if test ! -d "$i"; then
				echo "$NAME: Share $i does not exist."
				exit 1
			else
				conf_ok=1
			fi
		done
		IFS="$OIFS"
		if test -z "$conf_ok"; then
			echo "$NAME: No shares configured."
			exit 1
		fi
		return 0
	fi
	echo "$NAME: Configuration file does not exist."
	exit 1
}

case "$1" in

	start)
		check_shares
		start $NAME -- $MINIDLNA_ARGS 
		;;

	stop) stop $NAME;;
	status) status $NAME ;;
	restart) restart $NAME ;;
	*)
		echo "Usage: $0 {start|stop|status|restart}"
		exit 1
		;;
esac
