#!/bin/sh

DESC="CouchPotato searches and manages your movies"
NAME=couchpotato2
TYPE=user

USER=couchpotato2
GROUP=TV

DATA_DIR=/var/lib/couchpotato2
PROG_DIR=/opt/CouchPotato2
PROG=${PROG_DIR}/CouchPotato.py
CONFF=/etc/couchpotato2.conf

PID_PATH=/var/run/couchpotato2
PID_FILE=$PID_PATH/couchpotato2.pid

OPTS="--quiet --daemon --config_file=$CONFF --pid_file=$PID_FILE"

DL_DIR=$(sed -n 's/^to[[:space:]]*=[[:space:]]*\(.*\)/\1/p' $CONFF)

. $(dirname $0)/common

if ! test -d $PID_PATH; then
	mkdir -p $PID_PATH
	chown $USER:$GROUP $PID_PATH
fi

if test -e $PID_FILE; then
	PID=$(cat $PID_FILE)
	if ! kill -0 $PID >& /dev/null; then
		rm $PID_FILE
	fi
fi

if ! test -h /var/log/couchpotato2.log; then
    ln -sf $DATA_DIR/logs/CouchPotato.log /var/log/couchpotato2.log
fi

if test "$(basename $DL_DIR)" = "Public"; then
	echo "Fail: you have to configure CouchPotato2 first."
	exit 1
fi

if ! test -d "$DL_DIR"; then
	mkdir -p "$DL_DIR"
	chown $USER:$GROUP "$DL_DIR"
	chmod g+rwxs "$DL_DIR"
fi

case "$1" in
	start)
		echo -n "Starting $NAME: "
		start-stop-daemon -S -q -o --chuid $USER:$GROUP -x $PROG -- $OPTS
		omsg $?
		;;
	stop)
		echo -n "Stopping $NAME: "
		start-stop-daemon -K -q -o --pidfile $PID_FILE
		omsg $?
		;;
	status)
		if start-stop-daemon -K -t -q --pidfile $PID_FILE; then
			echo "$NAME running"
			exit 0
		else
			echo "$NAME stopped"
			exit 1
		fi
		;;
	restart)
		echo "Restarting $NAME: "
		sh $0 stop
		while sh $0 status >& /dev/null; do echo -n '.'; sleep 1; done
		sleep 5
		sh $0 start
        ;;
	*) usage $0 "start|stop|status|restart" ;;
esac
