#!/bin/sh

DESC="CouchPotato searches and manages your movies"
NAME=couchpotato
TYPE=user
NEED_ALTF_DIR=1

RC_USER=couchpotato
RC_USERN=20
RC_GROUP=TV
RC_GROUPN=200
RC_DESC="CouchPotato user"

DATA_DIR=/var/lib/couchpotato
PROG_DIR=/opt/CouchPotato
PROG=${PROG_DIR}/CouchPotato.py
CONFF=/etc/couchpotato.conf

PID_DIR=/var/run/couchpotato
RC_PIDFILE=$PID_DIR/couchpotato.pid

DL_DIR=$(sed -n 's/^destination[[:space:]]*=[[:space:]]*\(.*\)/\1/p' $CONFF)

OPTS="--quiet -d --nolaunch --config=$CONFF --datadir=$DATA_DIR --pidfile=$RC_PIDFILE"

. /etc/init.d/common

if test "$(basename $DL_DIR)" = "Public"; then
	check_user $PROG_DIR $CONFF
	echo "Fail: you have to configure CouchPotato first."
	exit 1
fi

for i in $PID_DIR "$DL_DIR"; do
	if ! test -d "$i"; then mkdir -p "$i"; fi
done

if ! test -h /var/log/couchpotato.log; then
    ln -sf $DATA_DIR/logs/CouchPotato.log /var/log/couchpotato.log
fi

chmod g+rwxs "$DL_DIR"

check_user $PROG_DIR $PID_DIR $CONFF "$DL_DIR"

case "$1" in
	start) start $PROG --chuid $RC_USER:$RC_GROUP -- $OPTS ;;
	stop) stop $NAME ;;
	status) status $NAME ;;
	restart) restart $NAME ;;
	*) usage $0 "start|stop|status|restart" ;;
esac
