#! /bin/sh

#set -x

NAME=mpd
TYPE=user
DESC="A flexible, powerful, server-side application for playing music"
NEED_ALTF_DIR=1

REQUIRE="avahi_daemon"

RC_USER=mpd
RC_USERN=23
RC_GROUP=multimedia
RC_GROUPN=81
RC_DESC="MPD daemon"

DATA_DIR=/var/lib/$NAME
CONFF=/etc/$NAME.conf

PID_DIR=/var/run/$NAME
PID_FILE=$PID_DIR/$NAME.pid

LOG_DIR=/var/log/$NAME

MUSIC_DIR=$(sed -n 's|^music_directory.*"\(.*\)"|\1|p' $CONFF)

MPD_DIRS="$PID_DIR $LOG_DIR"

RC_PIDFILE=$PID_FILE
RC_START_BG=yes
OPTS="--no-daemon"

. /etc/init.d/common

for i in $MPD_DIRS; do
	if ! test -d $i; then mkdir -p $i; fi
done

chmod g+rwxs "$MUSIC_DIR"

if ! grep -q "$(hostname)" $CONFF; then
	sed -i "s/^zeroconf_name.*/zeroconf_name \"Music Player on $(hostname)\"/" $CONFF
fi

check_user $MPD_DIRS

if test "$(basename $MUSIC_DIR)" = "Public"; then
	echo "Fail: you have to configure MPD first."
	exit 1
fi

case "$1" in
	start) start $NAME -- $OPTS;;
	stop) stop $NAME ;;
	status) status $NAME ;;
	restart) restart $NAME ;;
	*) usage $0 "start|stop|status|restart" ;;
esac

