#!/bin/sh

DESC="NZBGet is a binary newsgrabber for nzb files"
NAME=nzbget
TYPE=user
NEED_ALTF_DIR=1

RC_USER=nzbget
RC_USERN=21
RC_GROUP=TV
RC_GROUPN=200
RC_DESC="NZBget user"

CONFF=/etc/nzbget.conf
LOG_DIR=/var/log/nzbget
PID_DIR=/var/run/nzbget
RC_PIDFILE=$PID_DIR/nzbget.pid
DATA_DIR=$(sed -n '/^$MAINDIR=/s/$MAINDIR=\(.*\)/\1/p' $CONFF)

OPTS="--daemon -c $CONFF"

. /etc/init.d/common

umask 002

if test "$(basename $DATA_DIR)" = "Public"; then
	check_user $CONFF
	echo "Fail: you have to configure NZBget first."
	exit 1
fi

for i in $LOG_DIR $PID_DIR "$DATA_DIR"; do
	if ! test -d "$i"; then mkdir -p "$i"; fi
done

chmod g+rwxs "$DATA_DIR"
chmod g+rw,o-r $CONFF

check_user $CONFF $LOG_DIR $PID_DIR "$DATA_DIR"

case "$1" in
	start) start $NAME --chuid $RC_USER:$RC_GROUP -- $OPTS ;;
	stop) stop $NAME ;;
	status) status $NAME ;;
	restart) restart $NAME ;;
	*) usage $0 "start|stop|status|restart" ;;
esac

