#! /bin/sh

DESC="SickBeard searches and manages your TV shows"
NAME=sickbeard
TYPE=user
NEED_ALTF_DIR=1

RC_USER=sickbeard
RC_USERN=18
RC_GROUP=TV
RC_GROUPN=200
RC_DESC="Sick Beard user"

DATA_DIR=/var/lib/sickbeard
PROG_DIR=/opt/SickBeard
CONF_DIR=/etc/sickbeard
PID_DIR=/var/run/sickbeard

CONFF=$CONF_DIR/sickbeard.conf
PROG=${PROG_DIR}/SickBeard.py
LOG_FILE=/var/log/sickbeard.log
RC_PIDFILE=$PID_DIR/sickbeard.pid
DL_DIR=$(sed -n 's/^root_dirs.*=.*|\(.*\)/\1/p' $CONFF)

OPTS="--quiet --daemon --pidfile=$RC_PIDFILE --config=$CONFF --datadir=$DATA_DIR"

. /etc/init.d/common

if test "$(basename "$DL_DIR")" = "Public"; then
	check_user $CONF_DIR $PROG_DIR
	echo "Fail: you have to configure SickBeard first."
	exit 1
fi

if ! test -h $LOG_FILE; then ln -sf $DATA_DIR/Logs/sickbeard.log $LOG_FILE; fi

for i in $CONF_DIR $PID_DIR "$DL_DIR"; do
	if ! test -d "$i"; then mkdir -p "$i"; fi
done

chmod g+rwxs "$DL_DIR"

check_user $CONF_DIR $PID_DIR $PROG_DIR "$DL_DIR" 

case "$1" in
	start) start $PROG --chuid $RC_USER:$RC_GROUP -- $OPTS ;;
	stop) stop $NAME ;;
	status) status $NAME ;;
	restart) restart $NAME ;;
	*) usage $0 "start|stop|status|restart" ;;
esac
