#! /bin/sh

DESC="SickBeard searches and manages your TV shows"
NAME=sickbeard
TYPE=user

USER=sickbeard
GROUP=TV

DATA_DIR=/var/lib/sickbeard
PROG_DIR=/opt/SickBeard
PROG=${PROG_DIR}/SickBeard.py
CONFF=/etc/sickbeard/sickbeard.conf
DL_DIR=$(sed -n 's/^root_dirs.*=.*|\(.*\)/\1/p' $CONFF)

LOG_FILE=/var/log/sickbeard.log
PID_PATH=/var/run/sickbeard
PID_FILE=$PID_PATH/sickbeard.pid

OPTS="--quiet --daemon --pidfile=$PID_FILE --config $CONFF --datadir=$DATA_DIR"

. $(dirname $0)/common

if ! test -d $PID_PATH; then
	mkdir -p $PID_PATH
	chown $USER:$GROUP $PID_PATH
fi

if test -e $PID_FILE; then
	PID=$(cat $PID_FILE)
	if ! kill -0 $PID >& /dev/null; then
		rm $PID_FILE
	fi
fi

if ! test -h $LOG_FILE; then
    ln -sf $DATA_DIR/Logs/sickbeard.log $LOG_FILE
fi

if test "$(basename $DL_DIR)" = "Public"; then
	echo "Fail: you have to configure SickBeard first."
	exit 1
fi

if ! test -d "$DL_DIR"; then
	mkdir -p "$DL_DIR"
	chown $USER:$GROUP "$DL_DIR"
	chmod g+rwxs "$DL_DIR"
fi

case "$1" in
	start)
		echo -n "Starting $NAME: "
		start-stop-daemon -S -q -o --chuid $USER:$GROUP -x $PROG -- $OPTS
		omsg $?
		;;
	stop)
		echo -n "Stopping $NAME: "
		start-stop-daemon -K -q -o --pidfile $PID_FILE
		omsg $?
		;;
	status)
		if start-stop-daemon -K -t -q --pidfile $PID_FILE; then
			echo "$NAME running"
			exit 0
		else
			echo "$NAME stopped"
			exit 1
		fi
		;;
	restart)
		echo "Restarting $NAME: "
		sh $0 stop
		while sh $0 status >& /dev/null; do echo -n '.'; sleep 1; done
		sleep 5
		sh $0 start
        ;;
	*) usage $0 "start|stop|status|restart" ;;
esac
