#! /bin/sh

DESC="SABnzbd is a Binary Newsreader written in Python"
NAME=sabnzbd
TYPE=user
NEED_ALTF_DIR=1

RC_USER=sabnzbd
RC_USERN=19
RC_GROUP=TV
RC_GROUPN=200
RC_DESC="SABnzbd user"

DATA_DIR=/var/lib/sabnzbd
PROG_DIR=/opt/SABnzbd
PROG=${PROG_DIR}/SABnzbd.py
CONF_DIR=/etc/sabnzbd
CONFF=$CONF_DIR/sabnzbd.conf

PORT=$(awk '/[misc]/{ while (st = getline) { if ($1 == "port") {print $3; exit}}}' $CONFF)
DL_DIR=$(sed -n 's|^dirscan_dir *= *\(.*\)|\1|p' $CONFF)

PID_DIR=/var/run/sabnzbd
RC_PIDFILE=$PID_DIR/sabnzbd-$PORT.pid

OPTS="--daemon --pid=$PID_DIR --config-file $CONFF"

. /etc/init.d/common

if test "$(basename "$DL_DIR")" = "Public"; then
	check_user $CONF_DIR $PROG_DIR 
	echo "Fail: you have to configure SABnzbd first."
	exit 1
fi

if ! test -h /var/log/sabnzbd.log; then 
	ln -sf $DATA_DIR/logs/sabnzbd.log /var/log/sabnzbd.log
	ln -sf $DATA_DIR/logs/sabnzbd.error.log /var/log/sabnzbd-error.log
fi

for i in $PID_DIR "$DL_DIR"; do
	if ! test -d "$i"; then mkdir -p "$i"; fi
done

chmod g+rwxs "$DL_DIR"
chmod g+rw,o-r $CONFF

check_user $CONF_DIR $PROG_DIR $PID_DIR "$DL_DIR"

case "$1" in
	start) start $PROG --chuid $RC_USER:$RC_GROUP -- $OPTS ;;
	stop) stop $NAME ;;
	status) status $NAME ;;
	restart) restart $NAME ;;
	*) usage $0 "start|stop|status|restart" ;;
esac

