#! /bin/sh

set -e

DESC="Bittorrent client"
NAME=transmission-daemon
CONFF=/var/lib/transmission
JSON=settings.json
TYPE=user

OPTS="--logfile /var/log/transmission.log --config-dir=$CONFF"

TRANSMISSION_USER=transmission
TRANSMISSION_GROUP=network

. $(dirname $0)/common

case "$1" in
	start)
		eval $(awk '/"download-dir"/ { \
				gsub(",|\\\\", "", $2); printf "DOWNLOAD_DIR=%s;", $2 } \
			/"watch-dir"/ { \
				gsub(",|\\\\", "", $2); printf "WATCH_DIR=%s;", $2 } \
			/"incomplete-dir"/ { \
				gsub(",|\\\\", "", $2); printf "INCOMPLETE_DIR=%s;", $2 }' \
			"$CONFF/$JSON")

		if ! test -d "$DOWNLOAD_DIR" -a -d "$WATCH_DIR" -a -d "$INCOMPLETE_DIR"; then
			echo "Directories does not exist, you must configure transmission first. Exiting."
			exit 1
		fi

		network=$(hostname -i | awk -F. '{printf "%d.%d.%d.*", $1,$2,$3}')

		sed -i -e 's|.*"rpc-whitelist":.*|    "rpc-whitelist": "127.0.0.1,'$network'",|' \
			"$CONFF/$JSON"

		chown $TRANSMISSION_USER:$TRANSMISSION_GROUP "$CONFF/$JSON"

		echo -n "Starting $NAME: "
		start-stop-daemon -S -q -b -p /var/run/transmission.pid -m \
			--chuid $TRANSMISSION_USER:$TRANSMISSION_GROUP -x $NAME -- $OPTS
		omsg $?
		;;

	stop) stop $NAME ;;
	status) status $NAME ;;
	reload) reload $NAME ;;
	restart) restart $NAME ;;
	*) usage $0 "start|stop|status|restart|reload" ;;
esac
