#! /bin/sh

set -e

DESC="Run ffp initialization script"
TYPE=sys
NAME=ffp

. $(dirname $0)/common

case "$1" in
	start)
		echo -n "Starting $NAME: "
		if test -x /ffp/etc/rc; then
			/ffp/etc/rc start
			echo "OK."
		else
			echo "No ffp instalation found."
			exit 1
		fi
		;;
	stop)
		echo -n "Stopping $NAME: "
		if test -x /ffp/etc/rc; then
			/ffp/etc/rc stop
			echo "OK."
		else
			echo "No ffp instalation found."
			exit 1
		fi		
		;;
	status)
		if ! test -x /ffp/etc/rc; then
			exit 1
		fi
		;;
	restart)
		echo "Restarting $NAME: "
		sh $0 stop
		sleep 1
		sh $0 start
		echo ""
		;;
	*) usage $0 "start|stop|status|restart" ;;
esac

exit 0
