#! /bin/sh

DESC="Run ffp initialization script"
TYPE=sys
NAME=ffp

. $(dirname $0)/common

case "$1" in
	start)
		echo -n "Starting $NAME: "
		if test -x /ffp/etc/rc; then
			/ffp/etc/rc start
			echo "OK."
		else
			echo "No ffp instalation found."
			exit 1
		fi
		;;
	stop)
		echo -n "Stopping $NAME: "
		if test -x /ffp/etc/rc; then
			/ffp/etc/rc stop
			echo "OK."
		else
			echo "No ffp instalation found."
			exit 1
		fi		
		;;
	status) status $NAME ;;
	restart) restart $NAME ;;
	*) usage $0 "start|stop|status|restart" ;;
esac
