#! /bin/sh

DESC="Run user script"
TYPE=user
NAME=user

# inspired by "nogi"
BOOTLOG=yes
LOGF="alt-f.log"
SEP="======================"

. $(dirname $0)/common

bootlog() {
	if test -n "$BOOTLOG"; then
		logger "Services status:"
		rcall status
		for i in /mnt/*; do
			if mountpoint $i >& /dev/null; then
				writelog
			fi
		done
	fi
}

writelog() {
	echo -e "$SEP Alt-F $(cat /etc/Alt-F) $SEP\n" > $i/$LOGF
	date >>  $i/$LOGF

	echo -e "\n\n$SEP BOARD $SEP\n" >> $i/$LOGF
	cat /tmp/board >> $i/$LOGF

	echo -e "\n\n$SEP DMESG $SEP\n" >> $i/$LOGF
	dmesg >> $i/$LOGF

	echo -e "\n\n$SEP SYSLOG $SEP\n" >> $i/$LOGF
	logread >> $i/$LOGF

	echo -e "\n\n$SEP BOOTLOG $SEP\n" >> $i/$LOGF
	cat /var/log/boot.log >> $i/$LOGF

	echo -e "\n\n$SEP ETHTOOL $SEP\n" >> $i/$LOGF
	ethtool eth0 >> $i/$LOGF

	echo -e "\n\n$SEP IFCONFIG $SEP\n" >> $i/$LOGF
	ifconfig >> $i/$LOGF

	echo -e "\n\n$SEP ROUTE $SEP\n" >> $i/$LOGF
	route -n >> $i/$LOGF

	echo -e "\n\n$SEP RESOLVER $SEP\n" >> $i/$LOGF
	cat /etc/resolv.conf >> $i/$LOGF

	echo -e "\n\n$SEP HOSTS $SEP\n" >> $i/$LOGF
	cat /etc/hosts >> $i/$LOGF

	echo -e "\n\n$SEP RAID $SEP\n" >> $i/$LOGF
	if test -f /proc/mdstat; then
		cat /proc/mdstat >> $i/$LOGF
	else
		echo None  >> $i/$LOGF
	fi

	echo -e "\n\n$SEP MOUNT $SEP\n" >> $i/$LOGF
	cat /proc/mounts >> $i/$LOGF

	echo -e "\n\n$SEP TOP $SEP\n" >> $i/$LOGF
	top -n1 >> $i/$LOGF

	chmod a+rw $i/$LOGF
}

case "$1" in
	start)
		echo -n "Starting $NAME: "
		# to apply your own settings, create an external script and add
		# source/call it here; this way it will survive firmware upgrades.
		bootlog
		echo "OK."
		;;

	stop)
		echo -n "Stopping $NAME: "
		echo "OK."
		;;

	status)
		echo "$NAME stopped."
		exit 1
		;;

	restart) restart $NAME
		;;

	*) usage $0 "start|stop|status|restart" ;;
esac
