#! /bin/sh

DESC="Create diagnostics file and run user script"
TYPE=user
NAME=user

CONF_MISC=/etc/misc.conf

# inspired by "nogi"
LOGF="alt-f.log"
SEP="======================"

. $(dirname $0)/common

bootlog() {
	logger "Services status:"
	rcall status
	for i in /mnt/*; do
		if mountpoint $i >& /dev/null; then
			writelog
		fi
	done
}

writelog() {
	echo -e "$SEP Alt-F $(cat /etc/Alt-F) $SEP\n" > $i/$LOGF
	date >>  $i/$LOGF

	echo -e "\n\n$SEP BOARD $SEP\n" >> $i/$LOGF
	cat /tmp/board >> $i/$LOGF

	echo -e "\n\n$SEP Flashed Firmware $SEP\n" >> $i/$LOGF
	dd if=/dev/mtdblock2 ibs=64 count=1 2> /dev/null | strings >> $i/$LOGF

	echo -e "\n\n$SEP DMESG $SEP\n" >> $i/$LOGF
	dmesg >> $i/$LOGF

	echo -e "\n\n$SEP SYSLOG $SEP\n" >> $i/$LOGF
	logread >> $i/$LOGF

	echo -e "\n\n$SEP BOOTLOG $SEP\n" >> $i/$LOGF
	cat /var/log/boot.log >> $i/$LOGF

	echo -e "\n\n$SEP ETHTOOL $SEP\n" >> $i/$LOGF
	ethtool eth0 >> $i/$LOGF

	echo -e "\n\n$SEP IFCONFIG $SEP\n" >> $i/$LOGF
	ifconfig >> $i/$LOGF

	echo -e "\n\n$SEP ROUTE $SEP\n" >> $i/$LOGF
	route -n >> $i/$LOGF

	echo -e "\n\n$SEP RESOLVER $SEP\n" >> $i/$LOGF
	cat /etc/resolv.conf >> $i/$LOGF

	echo -e "\n\n$SEP HOSTS $SEP\n" >> $i/$LOGF
	cat /etc/hosts >> $i/$LOGF

	echo -e "\n\n$SEP RAID $SEP\n" >> $i/$LOGF
	if test -f /proc/mdstat; then
		cat /proc/mdstat >> $i/$LOGF
	else
		echo None  >> $i/$LOGF
	fi

	echo -e "\n\n$SEP MOUNT $SEP\n" >> $i/$LOGF
	cat /proc/mounts >> $i/$LOGF

	echo -e "\n\n$SEP TOP $SEP\n" >> $i/$LOGF
	top -bn1 >> $i/$LOGF

	chmod a+rw $i/$LOGF
}

user_script() {
	for cnt in $(seq 1 12); do
		if test -x "$USER_SCRIPT"; then
			"$USER_SCRIPT"
			return
		fi

		echo -n .
		sleep 10
	done
	echo "Fail: user script $USER_SCRIPT not found."
}

case "$1" in
	start)
		echo -n "Starting $NAME: "
		if test -f "$CONF_MISC"; then
			. $CONF_MISC
		else
			USER_LOGFILE="yes"
		fi

		if test "$USER_LOGFILE" = "yes"; then
			bootlog
		fi

		if test -n "$USER_SCRIPT"; then
			user_script
		fi

		echo "OK."
		;;

	stop)
		echo -n "Stopping $NAME: "
		echo "OK."
		;;

	status)
		echo "$NAME stopped."
		exit 1
		;;

	restart) restart $NAME
		;;

	*) usage $0 "start|stop|status|restart" ;;
esac
