#/bin/sh

CONF_OWNCLOUD=/etc/owncloud.conf
CONF_LIGHTY=/etc/lighttpd/lighttpd.conf
eval $(awk '/^var.server_root/{printf "sroot=%s", $3}' $CONF_LIGHTY)

echo -e "\n***************************************************************
ownCloud was installed in folder $(cat $CONF_OWNCLOUD)

As it might contain important data, it will not be deleted

You can delete the folder using the Setup->Folder web page
***************************************************************\n"

sleep 5