#!/bin/sh

THOME=/var/lib/transmission
JSON=settings.json

addgroup -S -g 81 network
adduser -S -g "Transmission daemon" -G network -u 13 -h $THOME transmission

if ! test -f $THOME/$JSON; then
	transmission-daemon -d -c "" -w "" --incomplete-dir ""  >& $THOME/$JSON
	sed -i -e 's|.*"peer-port-random-on-start":.*|    "peer-port-random-on-start": true,|' $THOME/$JSON
fi

chown transmission:network $THOME/$JSON
ln -sf /usr/sbin/rcscript /sbin/rctransmission
